### ISSUE TITLE
Removal of additional files breaks downstream reproducibility

### ISSUE THREAD

**Issue by dvzrv** [csound/csound#1072]
As seen on Arch Linux, [reproducible packaging breaks](https://bugs.archlinux.org/task/60846), because the additonal assets for documentation have been removed for 6.12.0 (and seem to be only available for 6.12.2).

Is there a specific reason as to why these files have been removed?

**Comment by vlazzarini** [comment]
some confusion with tagging might have caused this. I will fix it.

**Comment by vlazzarini** [comment]
fixed it

**Comment by dvzrv** [comment]
Thank you! :+1:

**Comment by dvzrv** [comment]
@vlazzarini okay, now I'm properly confused. :>

I have a package, that tracks the latest stable version (e.g. 6.12.2), but now the manual URL is wrong (6.12.0), so I can't track them together anymore.
The names of asset files should follow their respective version (they should all have 6.12.2 in the name), otherwise this gets very painful to package.

**Comment by vlazzarini** [comment]
I can change that.

**Comment by vlazzarini** [comment]
done.

**Comment by dvzrv** [comment]
Nearly alright: `Csound6.12.2_manual_pdf.zip` still contains `Csound6.12.0_manual.pdf`

This should be done in a scripted way, so there will be no rename/copy-paste problems.

**Comment by vlazzarini** [comment]
This is updated now. The problem was that there was a critical issue on MacOS/iOS which required a hotfix, then an issue with the Web platform was identified, needing another hotfix, and the new master was tagged 6.12.2 generating a new release. Since making packages is a collaborative effort, I did not request everyone to build new packages, just rearranged the releases as they were.

In a normal situation, this should not repeat.
