### ISSUE TITLE
printarray does not work with %d or %i format string

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1095]
it it very nice to have the printarray opcode now, and i like the design.
i have one bug report and two suggestions:
1. the %d or %i format string always leads to zero as output:
giArr1[] fillarray 1, 2, 3, 4, 5
printarray giArr1, "%d"
->   0: 0 0 0 0 0 
2. i don't like that there is always one extra newline in printout. can this be left as option to the user? for instance, this would give an extra newline:
printarray giArr1, "", "\n"
3. also i don't like the element count to have always.  it is very useful for long arrays, but should be optional, in my opinion.

**Comment by gesellkammer** [comment]
#1097 fixes this issue. Can we close it?

**Comment by jpffitch** [comment]
The bug is still there.  Ideally it should interpret %d as in printf style or throw an error on trying.  At the very least it should be noted in the manual.

There are two (I think) implementations of formatted printing in csound which interpret %d and others as expected.  Could it be possible to hook into that code?

**Comment by gesellkammer** [comment]
Should I take a look at what printf (the opcode) does and try to use 
that?

**Comment by joachimheintz** [comment]
if you can apply this for your code, it would be wonderful.
the problem is that users (like me) think they can use your format 
string in the same way as csound's printf.  as john mentioned, a minimal 
version would be to clarify on the manual page that it does *not* work 
like this, and that for getting integer output, %.0f should be used. 
but perhaps you can find a way.

**Comment by gesellkammer** [comment]
I took a  look at the code for printf and similar opcodes. Instead of copy pasting the parsing there, it would be nice to isolate the parsing in a function and include it in the api, or at least make it available via "#include". In concrete, the function `sprintf_opcode_` in `str_ops.c` could be extracted.
