### ISSUE TITLE
Building Lua opcodes on macOS

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#1101]
How do you build Csound’s [Lua opcodes](http://www.csounds.com/manual/html/lua.html) on macOS?

I’ve forked this repository and attempted to [build Csound with Lua opcocdes](https://travis-ci.org/nwhetsell/csound/builds/480176963). While a luaCsnd6.so file is [created](https://travis-ci.org/nwhetsell/csound/builds/480176963#L809) and [installed](https://travis-ci.org/nwhetsell/csound/builds/480176963#L1441), this file seems to be unusable on macOS, and Lua opcodes [don’t appear](https://travis-ci.org/nwhetsell/csound/builds/480176963#L2215) in Csound’s list of opcodes.

**Comment by gogins** [comment]
I don't work on OSX and therefore I'm sorry I can't answer this question
myself. But the luajit project page at luajit.org has build instructions
for OSX under the installation menu item.

**Comment by kunstmusik** [comment]
@nwhetsell I looked at the Lua Opcodes in 2011 and we dropped it on OSX due to compilation requirements that are not in our control. See:

http://csound.1045644.n5.nabble.com/OSX-Lion-OpenMP-and-crashes-td4900923.html#a4904209
http://csound.1045644.n5.nabble.com/Lua-opcodes-on-OSX-td5729252.html#a5729268

The same requirement for pagezero_size on OSX is still present on the luajit website under Embedding:

http://luajit.org/install.html

We can not package these opcodes for 64bit OSX or it will cause crashes in many use cases.

**Comment by nwhetsell** [comment]
@kunstmusik Thanks for this information.

I take it [linking with LuaJIT](http://luajit.org/install.html#embed) using `-pagezero_size 10000 -image_base 100000000` can’t be done for other reasons? (The reason I ask is because I use [LuaTeX](http://www.luatex.org), “an extended version of pdfTeX using Lua as an embedded scripting language”, which is available for macOS.)

At any rate, it might be a good idea to mention that Lua opcodes require Windows or Linux in Csound’s [documentation](https://csound.com/docs/manual/lua.html).

**Comment by kunstmusik** [comment]
@nwhetsell I think you'd need to be sure the top-level executable is compiled with those settings (which I assume LuaTex is), but in the use cases from 2011, there was no way to guarantee Java or Python were compiled with those settings. I'd assume the same if trying to use Csound via FFI from common lisp or scheme or ruby, etc.  It might work if you can control the environment, but we couldn't for general distribution, which is why we dropped it from packaging.
