### ISSUE TITLE
segfault on "bad" init

### ISSUE THREAD

**Issue by artificiel** [csound/csound#1124]
the following code segfaults. in isolation, the mistake is evident but not so easy to find in a larger orchestra. expected result is a parser error message indicating what the problem is.
```
<CsoundSynthesizer>
<CsInstruments>
instr 1
	g_peak[] init 2
endin
</CsInstruments>
<CsScore>
i1 0 1
</CsScore>
</CsoundSynthesizer>
```
tested on macOS 10.14.3 with 1b8a1a7cc3c89a44d193d93b873482dc2e5807d2

**Comment by jpffitch** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b10ab0 in create_array_arg_type (csound=csound@entry=0x61fe80,
     arrayVar=0x8525d0) at 
/home/jpff/csound6/Engine/csound_orc_semantics.c:190

**Comment by jpffitch** [comment]
My local version now says

csound -n gerr.csd
time resolution is 1000.000 ns
0dBFS level = 32768.0
--Csound version 6.13 beta (double samples) Mar  9 2019
[commit: a83b093539b21347b5427a04db49edf17f278628]
libsndfile-1.0.29pre1
Reading options from $HOME/.csound6rc
Reading options from local directory .csound6rc
UnifiedCSD:  gerr.csd
STARTING FILE
Creating orchestra
closing tag
Creating score
rtaudio: pulseaudio module enabled
rtmidi: ALSA Raw MIDI module enabled
error:  Array of unknown typeerror:  Unable to find opcode entry for 
'init' with matching argument types:
Found: @ init c
        g_peak init 2 ...
Line: 4
  from file gerr.csd (1)
Parsing failed due to syntax errors
Stopping on parser failure
cannot compile orchestra
end of score.              overall amps:      0.0
            overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.004s, CPU: 0.004s



Is that OK?

**Comment by jpffitch** [comment]
Rather an ugly patch so I should run it past Steven before closing this

**Comment by artificiel** [comment]
> Is that OK?

yes it makes sense!

**Comment by jpffitch** [comment]
Committed the simple patch.  Not perfect as it gives two error messages but it will suffice until all the type stuff is rewritten
