### ISSUE TITLE
Package Management Changes

### ISSUE THREAD

**Issue by stekyne** [csound/csound#1130]
This has been talked about for a while in conversation but I haven't really seen anyone take the initiative yet. Doing this would help me close #926 as I ran into some problems with fluidsynth as well. If there are already plans, can they be shared here?

As far as I can tell what needs to happen:
1. Create a new git repo under the Csound org on Github to house the opcodes. Maybe just "csound/opcodes".
2. Move out the following opcodes:
    1. Fluidsynth
    2. Ableton Link opcodes
    3. HDF5?
    4. Anything else that has a tricky dependency?
3. Clean up the CMake files for libcsound which will eliminate the need for some dependencies.
4. In the new repo, create a new CMake build.
    1. Need to get a hold of libcsound, probably need to host a binary somewhere and pull this down for each build. Could host this on github releases.
    2. Acquire all dependencies (based on platform). 
    3. Build each opcode and deploy somewhere?

How we do we allow the user to access this opcodes then? There was the idea of the package manager. Any feedback is welcome.

**Comment by vlazzarini** [comment]
I think it is a good idea, but prefer to separate each opcode set with different dependencies. So, for example, fluidsynth could go to their own repo.

**Comment by stekyne** [comment]
Would that be under the csound org set of git repos or a completely external one?

**Comment by jpffitch** [comment]
I dd move most opcodes out of te base and into loadable libraries -- that 
was the reason for Opcodes directory as distinct from OOps (== Old Ops) 
but that was a problem with Android etc

Has this changed?

**Comment by gsenna** [comment]
> Would that be under the csound org set of git repos or a completely external one?

I'd say external ones. Ideally, shouldn't new plugins have their own creators/maintainers? And if we end up using a package manager, then the csound organization could just curate and distribute a list like [this](https://github.com/supercollider-quarks/quarks/blob/master/directory.txt) one.

**Comment by stekyne** [comment]
That's true and we should support that but a lot of plugins can be very small also and possibly have no dependencies. I think to get them to create a git repo, create a build system/binary output and then add it to our list is a lot of work. I was thinking having a git repo in our org that people could pull request their own modules/code would be way of making it easier for people to create opcodes.

**Comment by gogins** [comment]
The critical thing here is a package system for installing opcodes from
URLs. That is more important than how opcode repositories are done.

Ideally the package system would detect what platforms each inside is
supported on.

Perhaps there could be a build server for all platforms.

**Comment by stekyne** [comment]
Well it's another part of it. This is the first stage of moving it out. How it gets onto a client machine can come later.

There are binary artifact hosting services like bintray which could store the output for multiple platforms. Obviously the package manager knows what kind of system it's running on so we can just pull the appropriate ones down. We still don't have a design (as far as I know) for how it will work so I'm only concerned with getting the build system and CI/binary deployment working.

**Comment by gsenna** [comment]
I plan to explore building a system with [conan](https://conan.io), which unfortunately it's written in python. I couldn't find anything more suitable.

**Comment by fsateler** [comment]
> This is the first stage of moving it out

I'd say the package manager needs to come first, to avoid usability breaks. Otherwise, how are users supposed to install the other opcodes?

**Comment by stekyne** [comment]
That's true. We're not going to get this all done in one big bang approach though. The first step is just getting the source out of tree and still maintain the current packaging. So building and shipping Csound with all the opcodes. We can still maintain this and move them out into a separate repo(s), as long as the CI packages them still. So if we can aim for that and at least have a platform to build the package manager on, then I think that this iterative approach will work best.

**Comment by fsateler** [comment]
> So building and shipping Csound with all the opcodes.

Ah, I didn't quite get that. 

It would still require me to package that separately for debian, wouldn't it? Or source distribution would include the opodes?

**Comment by stekyne** [comment]
I'm not really familiar with how that works. Is it written down anywhere? Where are the Debian packages built? For the time being, we could include the opcodes as a git submodule or something like that. I guess we need to figure out all the scenarios here first before continuing. I'll document it in the wiki as we figure it out.

**Comment by jpffitch** [comment]
The package manager must be in place before changes.  We need certainty that it exists and works in a clear way.  I though this was discussed a long time bck and the package manager was sort of promised soon.  I await a design or candidate code, and a plan to implement it.

**Comment by stekyne** [comment]
https://github.com/csound/csound/wiki/Package-Management I've started a wiki page to document any research and the proposed solution. Still a work in progress but feel free to comment or make changes.

**Comment by gsenna** [comment]
Just a quick update from my part: 

I was working on creating cross-platform installers for Csound (with automatic updates) using the Qt IFW. But now, while preparing things for the launch of Qt 6, the Qt organization seems to be dabbling with the idea of dropping this framework and instead to rely on other existing solutions. Or perhaps something new that complements those solutions, they don't seem to know yet. Whichever one it is, in their bug tracking platform you can find very recent POCs that were created with the intention of exploring conan and vcpkg as the alternatives.

I think this could be good news for us because they might put something together that we can use, like  a new installer framework created on top of a package manager like conan . Or they might just leave us without an installer framework...

**Comment by stekyne** [comment]
That's interesting.  Is our installer basically just for Windows and Mac by the way?

**Comment by gsenna** [comment]
I'm aiming at supporting Windows, Mac and Linux, but only for the desktop. Is that right?

**Comment by stekyne** [comment]
Right, as far as I know. For Linux, is the installer really needed or is the package manager(s) enough?

**Comment by gsenna** [comment]
If Travis is the one that is going to build the installer for Linux, then it would be nice to support that too.

By the way, this is the [Qt POC](https://bugreports.qt.io/browse/QTBUG-74362) I'm currently following.

**Comment by jpffitch** [comment]
What do yu mea by the desktop?  Personally I do not have one.

**Comment by gsenna** [comment]
I meant not for mobile devices. Although we could include "Csound for the Web" as a package.

**Comment by gogins** [comment]
I'm going to weigh in here with some suggestions. These are based on my experience with apt and npm. Also LaTeX and Python have similar systems. 

I suggest the following design requirements for Csound Packages (CPs), the Csound Package
Manager (CPM), a Csound Packaging Tool (CPT), and Csound Package Archives
(CPAs).

-- CPM should be part of the core Csound library,

-- The Csound command line options should be extended with CPM commands (--cpm)
   modeled upon apt or npm, such as: install uninstall update upgrade list
   contents, e.g. "--cpm-install http:/bozo/my_csound_plugins.cp" or, if there 
   is a local registration of its CPA, just "--cpm-install my_csound_plugins".

-- The Csound orchestra language #include statement should be extended to
   itegrate with the CPM using a "from" attribute, e.g. #include "my_instr.inc"
   from "http://bozo/my_csound_instrs.cp".

-- CPs should follow a standard yet extensible layout, supporting all kinds of
   resources, including Csound pieces, UDOs, and binary plugins. Resources that
   depend on architecture should be placed into architecture-specific folders.
   The npm package.json format might serve as an example.

-- CPM should be able to install or update packages from local files or from the
   Internet using regular URIs.

-- There should be a Csound Packaging Tool (CPT) too, also maintained and
   released from the Csound repository.

-- CPAs should feature a simple layout of publicly available CPs. 

-- Of course, CPM and CPC should run on all the platforms that Csound itself
   runs on.

-- There should be source CPs and binary CPs. As with npm and node-gyp there
   should be a standard way to build a binary CP from a source CP on every
   Csound platform and architecture.

-- Ideally, and this is the big one, CPAs should use continuous integration to
   automatically build binary extensions from source code on requested
   architectures. The expectation should be that a CP author working on one
   platform using cross-platform code can find his or her CP built for other 
   platforms, or at least an available error log so that the next checkin to the 
   CPA will trigger a new build.

-- Idiot-proof documentation for all this should be online and in the Csound 
   Reference Manual.

**Comment by stekyne** [comment]
Including the CPM with the Csound driver I think is a recipe for disaster. Doing that kind of network heavy app in C is not pleasant and it will basically be difficult and riddled with bugs. More importantly probably no one will do it. Not to mention futher bloat in an already sizable command line app. 

Including all types of Csound content is a great endeavour but realistically sharing around text files vs sharing platform specific compiled binary files (with their own platform specific build depdendencies) is very different. We need clear definitions on what is expected and how the language will deal with each type. It's easy to say "share all kinds of resources". Where on the system will they go? How are they resolved? How are errors communicated? Are all these files local or per project? Do pieces/UDOs/other text files really need to be versioned? Are we handling compatibility or is the latest always assumed? 

"As with npm and node-gyp there should be a standard way to build a binary CP from a source CP on every Csound platform and architecture." Do you mean on any client or on the CI? Straight away on Windows this is going to be a pain in the case of opcodes with other binary dependencies.

We don't need an NPM for Csound, that's way too grand a task and we don't even have the requirements to justify it (nor the development resources). None of the other 3 music programming language package managers you mentioned elsewhere are as complicated as what you describe. We need to be more pragmatic about it and build a simple system that works.

**Comment by gogins** [comment]
Thanks for your comments.

We DO need an npm for Csound, but it doesn't have to be as heavy as npm.

I will respond to your comments as follows.

> Doing that kind of network heavy app in C is not pleasant and it will basically be
> difficult and riddled with bugs.

No need to re-invent the wheel. Use libcurl or something, already
debugged, as a shared library adds no bloat to Csound. I regard this
comment as a straw man.

> Including all types of Csound content is a great endeavour but realistically sharing around
> text files vs sharing platform specific compiled binary files (with their own platform specific
> build depdendencies) is very different.

You are quite correct about build dependencies. This is actually the
major problem. The easiest solution is for the package to complain
about unmet dependencies. And there should be a set of dependencies
that can be assumed to be present, more or less the same as the ones
used by Csound itself, that are spelled out for extension developers.

> We need clear definitions on what is expected and how the language will deal with each type.
> It's easy to say "share all kinds of resources". Where on the system will they go?

As long as they are similar to the resources already installed for
Csound, they go in the same places. If they are different, the package
definition tells CPM where to put them.

> Do pieces/UDOs/other text files really need to be versioned? Are we handling compatibility
> or is the latest always assumed?

This also is a valid point. Compatibility cannot be assumed. Things
must be versioned. I suggest versioning them the same way as with
Linux sonames. Perhaps a better alternative is like the snap system,
to bundle all binary dependencies in a Csound tree.

> "As with npm and node-gyp there should be a standard way to build a binary CP from a source CP
> on every Csound platform and architecture." Do you mean on any client or on the CI? Straight away
> on Windows this is going to be a pain in the case of opcodes with other binary dependencies.

I mean for continuous integration, but if it works there it should be
adaptable to personal computers. Windows is a pain, but node-gyp can
do it. Many of the continuous integration systems can run locally,
that might be a solution.

> We don't need an NPM for Csound, that's way too grand a task... None of the other 3 music
> programming language package managers you mentioned elsewhere are as complicated...
> We need to be more pragmatic about it and build a simple system that works.

I AM being pragmatic. I know from experience that if you push the
complexity down in one place, it pops up again in another place. The
other package managers are partial solutions. The complexity they push
down pops up again in the need for every extension developer to
re-invent the build system and the packaging tools.

If Csound offers a partly implemented package system, then the issues
not dealt with will inevitably pop up again in the form of additional
complexity not only for the installer maintainers, but also for the
extension developers, and the package maintainers.

I understand these are real problems that do not go away. On Debian
the apt system is not completely satisfactory and has led to the
development of the snap system, where an application is installed with
its own /usr tree and shell environment, including all binary
dependencies.

Best,
Mike







----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
Closing as out-of-date. Since the last activity on this ticket, plugins have a new repo and @gesellkammer has written [risset](https://github.com/csound-plugins/risset). Regardless, package management should be done as a separate project from core Csound.
