### ISSUE TITLE
[Legal] csound cannot be packaged

### ISSUE THREAD

**Issue by krop** [csound/csound#1148]
Issue found while reviewing a package update for openSUSE.

csound uses files which require permission from the copyright holders before being distributed.

The license header in Opcodes/scansyn.c and Opcodes/scansynx.c states that:

> Permission to use, copy, or modify these programs and their documentation
> for educational and research purposes only and without fee is hereby
> granted, provided that this copyright and permission notice appear on all
> copies and supporting documentation. **For any other uses of this software,
> in original or modified form, including but not limited to distribution in
> whole or in part, specific prior permission from Interval Research must be
> obtained.** Interval Research makes no representations about the suitability
> of this software for any purpose. It is provided "as is" without express or
> implied warranty.

This is a blocker for all distributions, we're not allowed to package and distribute csound to our users.

**Comment by fsateler** [comment]
This has been known for a long time. Currently in debian we strip the scansyn opcodes from the tarball. It would be nice to have the situation clarified.

**Comment by jpffitch** [comment]
It is a plugin library so setting BUILD_SCANSYN_OPCODES to off stops it 
being built and deleting Opcodes/scansyn* removes the sources.  I thught 
that was sufficient.

**Comment by krop** [comment]
Nope, for openSUSE, we'll cripple the tarball and disable this plugin.
However, as the upstream project, csound is also not allowed to distribute these files without Interval Research's permission.
As this company closed its doors in 2000 and its successor, Interval Media closed in 2006, csound is probably not allowed to include these files in any release.

**Comment by vlazzarini** [comment]
I thought we had written permission from
the authors to distribute these.

**Comment by krop** [comment]
> I thought we had written permission from
> the authors to distribute these.

Note that the person who coded these files (Paris Smaragdis) is not the copyright holder.

**Comment by vlazzarini** [comment]
I know that and I did not mean Paris.
I thought we had written permission from the copyright owners.

**Comment by kunstmusik** [comment]
https://patents.google.com/patent/US6647359 mentions the original patent filed July 17th, 1999. I think US patents expire after 20 years.  Is there a path that allows us to provide a cleanly licensed version of this file? (Perhaps a clean rewrite?)

**Comment by jengelh** [comment]
> https://patents.google.com/patent/US6647359 mentions the original patent filed July 17th, 1999. I think US patents expire after 20 years.

Patents and copyright are two separate things, though.

**Comment by vlazzarini** [comment]
I am closing this. I think it's clear that we have had the right to distribute this code since it was added to the Csound codebase. If distributions have an issue with that, there is nothing we can do.

**Comment by krop** [comment]
So, where is the written permission?

**Comment by vlazzarini** [comment]
Permission was given by Bill Verplank to Richard Boulanger. You can ask him directly.

**Comment by krop** [comment]
Even if that's true, that doesn't fix the issue.

**Comment by vlazzarini** [comment]
What do you mean by "even if this were true"? Are you saying Richard has lied to us?

It's a complete non-issue.

**Comment by krop** [comment]
> I know that and I did not mean Paris.
> I thought we had written permission from the copyright owners.

This was your answer months ago.
And again, even if the csound project got such agreement with the copyright holder, distributions don't.
It's not a matter whether we're satisfied or not. We're legally not allowed to distribute this software.

**Comment by kunstmusik** [comment]
My two cents:

Long term: Let's schedule to move the scanned synthesis files to an external opcode library and have it in a separate repository since the files have been questioned before. We are going to move out other libraries in CS7 and we can consider these as part of that work. This should have no net effect on existing users as our other distributions/platforms (e.g., Windows, Mac) can package in the binary plugins, while Linux distributions which depend on source releases are already stripping this out. 

Short term: For CS6, to not disrupt the other distribution/ecosystems and so as to not duplicate work, let's keep this in as there are well-known workarounds (i.e., what Debian has been doing for man years now). 

One other option I can think of: We can put together a source zip/tarball release that does not include the scanned opcodes.  (e.g., csound-6.15.0-src-noscanned.zip) If we publish that as part of our releases, the file would stay within our repo but be removed for downstream to depend upon.  Would that satisfy @krop for OpenSUSE?  (and @fsateler for Debian?) I am assuming downstream is not building from git.

**Comment by krop** [comment]
To work around the issue, the package maintainer pulls locally from git and Opcodes/scansyn* files are removed before repacking the file.
The unused util/new_srconv.c file is also deleted for a different reason: it's an unused GPL-2.0-or-later file in the middle of LGPL-2.1-or-later ones (and csound claims to be LGPL-2.1-or-later)

**Comment by jpffitch** [comment]
what do you mean unused util/new_srconv.c ?  It is used and is 
deliberately a separate program.  I checked with Erik who holds copyright 
for the lisamplerate library that what i did was witin the licences.

**Comment by gogins** [comment]
All of the Csound source code needs to be compatible with the LGPL v2.1
because this contains a clause permitting redistribution under "any later
version" that enables the code to be conveyed as GPLv3 (see the official
Free Software Foundation compatibility matrix at
https://www.gnu.org/licenses/gpl-faq.html#v3HowToUpgrade). If we have plain
LGPL v2 for anything we should try to get permission to change that.

What prevents us from obtaining written permission for the scanned
synthesis code?

Best,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com
