### ISSUE TITLE
Change of naming of the CsoundQT App

### ISSUE THREAD

**Issue by Daz-wallace** [csound/csound#1158]
Hi folks,

We package and deploy Qsound and QTSound for Mac for a customer.

It appears that in the latest release disk image (Csound6.13.0), the "CsoundQt-d-py-cs6" App bundle was renamed to "CsoundQt-d-html-cs6".

Is the newer *html* version a direct replacement of the *py* version, or a different App altogether? 

Thanks!

**Comment by jpffitch** [comment]
Probably better to ask this on csoundQt list or csound developers' list as it does not relate to csound per se

⁣Sent from TypeApp ​

**Comment by Daz-wallace** [comment]
Thanks I’ll also ask there. 

The other reason is that csoundQT is included in the Csound release disk image so I thought one of the devs here may know why?

Thank!

**Comment by kunstmusik** [comment]
Reiterating that this isn't really a Csound issue and should be asked on CsoundQt's mailing list or emailed to their developers. The naming reflects what features were enabled during compilation. This was discussed on the Csound list that the python feature is not compiled in now due to conflicts with various people's python installations.  The HTML feature for users to create interfaces was compiled in, hence -html .  A version with python is available from the CsoundQt site. Check out their release notes:

https://github.com/CsoundQt/CsoundQt/releases/tag/0.9.6

Closing this issue.
