### ISSUE TITLE
Csound 6.13 in Catalina 10.15.2 trying to open libraries in version 6.0 instead of Current

### ISSUE THREAD

**Issue by xenophoria** [csound/csound#1236]
I am trying to get CsoundQt running on a MacBook Pro running **Catalina 10.15.2**. I recently reinstalled **Csound 6.13** and **CsoundQt 0.9.6**. Warnings indicate Csound is trying to open libraries in version **6.0** instead of **Current**. CSD files appear to render successfully unless they involve realtime output and include FLTK code. 

**e.g. 1 : with FLTK** 

```
; Select audio/midi flags here according to platform 
; Audio out Audio in No messages -odac -iadc -d 
;;;RT audio I/O 
; For Non-realtime output leave only the line below: 
; -o linseg.wav -W 
;;; for file output any platform 
;******************************* 
sr = 44100 
kr = 32 
nchnls = 2 
0dbfs = 1 ;

*** It is recommended to put almost all GUI code in the 
;*** header section of an orchestra FLpanel "Panel1",450,550 
;***** start of container
; some widgets should contained here FLpanelEnd 
;***** end of container FLrun 
;***** runs the widget thread, it is always required! 

instr 1 
;put some synthesis code here 
endin 

;******************************* 
f 0 3600 ;dummy table for realtime input 
e 

</CsScore>
</CsoundSynthesizer>
```
If I render it I get a panel labelled _Panel1_ with a beach ball crash i.e. -> Force Quit CsoundQt-d-py-cs6 (not responding). 

**e.g. 2 : without FLTK** 

If I render a CSD file with no FLTK, CsoundQt runs fine with the following warnings 

`WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjacko.dylib' (-1) WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libfluidOpcodes.dylib' (-1) WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjackTransport.dylib' (-1) WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/librtjack.dylib' (-1) 
`

**e.g. 3 : In Terminal**

These Terminal messages might explain the crash in **e.g. 1** and warnings in **e.g. 2** 

`gs@Gregorys-MacBook-Pro-2 Versions % pwd

/Library/Frameworks/CsoundLib64.framework/Versions gs@Gregorys-MacBook-Pro-2 Versions % 

ls -l 
drwxrwxr-x 6 root wheel 192 9 Nov 20:49 6.0
lrwxr-xr-x 1 root wheel 3 12 Dec 07:11 Current -> 6.0 
`

My bogan instinct tells me that **Current -> 6.0** may be too general. Is it possible this setting is no longer applicable in Catalina 10.15.2 ? What happens if the newest Csound opcodes are found in version 6.0 but Catalina 10.15.2 requires newer Java and Python scripts ? 

While I don't know the answers the crash I provided clearly demonstrates that these warnings require attention. I'd be grateful if anyone can advise me how to respond. Thanks. 

BTW, apologies for posting this here. I tried posting it on CSOUND@LISTSERV.HEANET.IE but it was rejected. I am having a lot of trouble posting messages on Nabble. After signing up recently I discovered old messages that I posted there back in 2011. My latest rejected post is the fifth attempt in as many days and I'm confident my messages do not violate the forum's policy. Rejections are more likely the result of some rogue setting caused by signing up more than once using the same email address. I have notified CSOUND-request@LISTSERV.HEANET.IE and have received a silicon-based response. I am now looking forward to a protein-based response for Christmas. So if you have a way to notify Santa please pass this on. Thanks in anticipation.

Greg S

**Comment by vlazzarini** [comment]
I think it could be that FLTK simply does not work in Catalina anymore.

The other warnings are because you do not have the Jack connection kit installed. You can ignore them, or install jack.


Prof. Victor Lazzarini
Maynooth University
Ireland

On 20 Dec 2019, at 07:12, Greg Schiemer <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to get CsoundQt running on a MacBook Pro running Catalina 10.15.2. I recently reinstalled Csound 6.13 and CsoundQt 0.9.6. Warnings indicate Csound is trying to open libraries in version 6.0 instead of Current. CSD files appear to render successfully unless they involve realtime output and include FLTK code.

e.g. 1 : with FLTK

; Select audio/midi flags here according to platform
; Audio out Audio in No messages -odac -iadc -d
;;;RT audio I/O
; For Non-realtime output leave only the line below:
; -o linseg.wav -W
;;; for file output any platform
;*******************************
sr = 44100
kr = 32
nchnls = 2
0dbfs = 1 ;

*** It is recommended to put almost all GUI code in the
;*** header section of an orchestra FLpanel "Panel1",450,550
;***** start of container
; some widgets should contained here FLpanelEnd
;***** end of container FLrun
;***** runs the widget thread, it is always required!

instr 1
;put some synthesis code here
endin

;*******************************
f 0 3600 ;dummy table for realtime input
e

</CsScore>
</CsoundSynthesizer>


If I render it I get a panel labelled Panel1 with a beach ball crash i.e. -> Force Quit CsoundQt-d-py-cs6 (not responding).

e.g. 2 : without FLTK

If I render a CSD file with no FLTK, CsoundQt runs fine with the following warnings

WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjacko.dylib' (-1) WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libfluidOpcodes.dylib' (-1) WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjackTransport.dylib' (-1) WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/librtjack.dylib' (-1)

e.g. 3 : In Terminal

These Terminal messages might explain the crash in e.g. 1 and warnings in e.g. 2

`gs@Gregorys-MacBook-Pro-2 Versions % pwd

/Library/Frameworks/CsoundLib64.framework/Versions gs@Gregorys-MacBook-Pro-2 Versions %

ls -l
drwxrwxr-x 6 root wheel 192 9 Nov 20:49 6.0
lrwxr-xr-x 1 root wheel 3 12 Dec 07:11 Current -> 6.0
`

My bogan instinct tells me that Current -> 6.0 may be too general. Is it possible this setting is no longer applicable in Catalina 10.15.2 ? What happens if the newest Csound opcodes are found in version 6.0 but Catalina 10.15.2 requires newer Java and Python scripts ?

While I don't know the answers the crash I provided clearly demonstrates that these warnings require attention. I'd be grateful if anyone can advise me how to respond. Thanks.

BTW, apologies for posting this here. I tried posting it on CSOUND@LISTSERV.HEANET.IE<mailto:CSOUND@LISTSERV.HEANET.IE> but it was rejected. I am having a lot of trouble posting messages on Nabble. After signing up recently I discovered old messages that I posted there back in 2011. My latest rejected post is the fifth attempt in as many days and I'm confident my messages do not violate the forum's policy. Rejections are more likely the result of some rogue setting caused by signing up more than once using the same email address. I have notified CSOUND-request@LISTSERV.HEANET.IE<mailto:CSOUND-request@LISTSERV.HEANET.IE> and have received a silicon-based response. I am now looking for to a protein-based response for Christmas. So if you have a way to notify Santa please pass this on. Thanks in anticipation.

Greg S

**Comment by xenophoria** [comment]
Thanks for your suggestion Professor Lazzarini. Jack may well be causing the crash not FLTK. I will try and address warnings by installing it again manually using brew. It might also be worth trying to override **Current -> 6.0** first to see if warnings disappear and CsoundQt runs FLTK widgets. 

Re FLTK not working with Catalina, would this mean building a UI in javascript (like some of the html files in https://waaw.csound.com) ? This could be the way to create a UI that is close to my iOS app.

Greg S

**Comment by vlazzarini** [comment]
I don’t think CsoundQT can run FLTK widgets. If you are using CsoundQT you can’t use FLTK, they are incompatible.
========================
Prof. Victor Lazzarini
Maynooth University
Ireland

**Comment by vlazzarini** [comment]
Btw, the warnings have nothing to do with the install location and directory names. If that were the case, all opcodes would not be loaded or found. The opcodes have been found, but they could not be loaded. Three of them are to do with the Jack library not being found (probably not installed or not installed correctly).

```
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjacko.dylib' (-1) WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjackTransport.dylib' (-1) WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/librtjack.dylib' (-1)
```

The other one is to do with the fluidsynth library, where I know there was a linkage name problem, which I thought I solved in the latest installer, but it could have resurfaced.

```
'/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libfluidOpcodes.dylib' (-1) WARNING: could not open library 
```
