### ISSUE TITLE
missing libraries in Appveyor installer 

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1237]

**Comment by Oeyvind** [comment]
Running csound after installing with the 6.14.425 installer from
https://ci.appveyor.com/project/csound/csound/build/artifacts
It will not run, due to missing library:
vorbisenc.dll
vorbis.dll
ogg.dll

**Comment by stekyne** [comment]
Damn must have missed those. I'll add them to the installer shortly. In the mean time you can download the artifact: https://ci.appveyor.com/api/buildjobs/7y60or8cf2p6tyff/artifacts/csound-windows_x86_64-6.13.0-425.zip and extract the missing files into the bin dir.

**Comment by stekyne** [comment]
I think the issue is that the csound/plugins directory is not in the path. This is where those libs are stored, not the Csound bin directory. That's maybe not quite correct but it seems to be the way it is. You should add that path to the directory but we may need to not give the option in the installer anymore. Seeing as it breaks the installation. On the other hand, I had thought I made libsndfile statically linking into the build now so those dependencies shouldn't be as shared libs either. I'll do a bit more digging.

**Comment by Oeyvind** [comment]
I downloaded an Appveyor build a few days ago and ran it here on Windows 10. It did not produce any errors, so the issue is probably solved. I did check to see that I do not have the csound/plugins directory in my path, so I assume it now works likewise for other users.
