### ISSUE TITLE
some links on getting started page broken

### ISSUE THREAD

**Issue by whompyjaw** [csound/csound#1241]
under the section "Your first synthesizer" the first paragraph has links that 404.

"Now that the basics of the Csound language have been outlined, it’s time to look at creating a simple instrument. The opcodes used in this simple instrument are **vco2**, **madsr**, **moogladder** and **out**."

https://csound.com/get-started.html#your-first-synthesiser

**Comment by whompyjaw** [comment]
Also, the 3rd paragraph has a statement that I don't understand. 
"An x before an input argument indicates that i, k or a-rate variables can be used" which is referring to 
**ares vco2 kamp, kcps [, imode] [, kpw] [, kphs] [, inyx]**
but there is no 'x' before any of the input arguments. What am I missing? Can this be clarified?

**Comment by vlazzarini** [comment]
This is the Csound software repo tracker, you need to open a ticket on the csound.github.io tracker for website items so it can get attention (different people take care of that)

**Comment by joachimheintz** [comment]
hi and thanks for the report -

i have fixed the 404 links.

as to your x-question: you can see an example in
https://csound.com/docs/manual/vco.html

the vco2 has no x-argument, so this is not a good example.  i have modified the text; so hopefully it is more clear now.

i understand that you reported here, because the "report a bug" link only guides you here.  i will try to make a page which lists the several parts of csound so that in future we get the reports to the proper locations.

cheers -
    joachim
