### ISSUE TITLE
Segmentation violation in Windows Csound 6.14 with -M0 realtime option

### ISSUE THREAD

**Issue by arthunkins** [csound/csound#1333]
With MIDI device attached and only -M0 and -odac in CsOptions, a segmentation violation occurs during command-line program execution. (An I-time only run is fine.) Csound returns to the C: prompt, and runs normally afterward. 

A test file is found in issue #1324 filed two weeks ago. The default MIDI device, PortMidi, *is* found and activated, following which the segmentation violation occurs. None of this happens with Csound 6.13 (again, Windows). Also, this problem is not present for the Mac OS.

Note that the test file does not include any MIDI activity itself. Also note that other MIDI drivers, when selected via the -+rtmidi option (e.g., Winmm), do not cause the violation, and process MIDI information as expected.

**Comment by jpffitch** [comment]
I see no crash on Linux.

**Comment by jpffitch** [comment]
So it appears to be a portmidi problem on windows and not csound's error

**Comment by kunstmusik** [comment]
I took a look at this and have segfaults here too. I don't see anything in code that seems off. What I did figure out so far:

1. For 6.13.0, we built portmidi from SVN. Since then, our build system changed to use the version contained in vcpkg.  
2. I think we are now dynamically linking to portmidi. I believe we were statically linking prior but that needs confirmation.

@stekyne Perhaps you can help me diagnose this?
