### ISSUE TITLE
pvsfreeze oddity

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1440]
It seems pvsfreeze does not freeze cleanly, and also does not unfreeze after being used.
The attached code
[freezetest.zip](https://github.com/csound/csound/files/6027814/freezetest.zip)
shows a pulsed sine fed into pvsfreeze, with freezing disabled at the start, then enabled and disabled again.
There are 2 issues: 
- freezing does not seem to freeze the signal, but creates a half-frozen looping sound
- after freeze has been disabled, the signal is smeared

**Comment by vlazzarini** [comment]
So I had a look at this and:

- freezing is as expected. Your window size is 8192, that's nearly 200ms at 44.1 KHz, reducing the window gives
a frozen sinusoid. The window chosen (0 - hamming) is not ideal as it doesn't go to 0 at the edges. Change to 1 for
better results.

- Unfreezing is actually strange. I'll have to investigate what's going on. It should just give the input signal after a short transient time.

**Comment by vlazzarini** [comment]
I examined the code and all is as expected. The unfreezing in this case is working as expected, but the smearing is to do with the particular conditions of the example and is to do with the frequency freezing. As you unfreeze it, an offset is added to the phases (this is what I am supposing) which tends to cause a side-effect in this example because of the periodic nature of it. Now, if you only freeze the amplitudes, then when you unfreeze, the input and output are the same.

Here's the test. I made a few small modifications to your code. First, I am using a hanning window (1) and secondly,  I added a delay to compensate the pvs latency. So you can  hear the two channels in sync, then amplitude is frozen, then they are back in sync when unfrozen. If you freeze the frequencies, then the phase smearing effect appears at the unfreezing stage. I would suspect that this is particular to the type of test being used here.

```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

  sr = 44100
  ksmps = 256
  nchnls = 2
  0dbfs=1


instr 1

  kamp init 1
  kmetro metro 6
  kamp = (kamp+kmetro)%2
  a1 oscil kamp*0.5, 440
  
  ; freeze
  kfreeze linseg 0, p3/3, 0, 0, 1, p3/3, 1, 0, 0, p3/3, 0
  ifftsize = 8192
  ioverlap = ifftsize/4
  printk2 kfreeze

  f1 pvsanal a1, ifftsize, ioverlap, ifftsize, 1
  freez	pvsfreeze f1, kfreeze, 0
  af1	pvsynth freez
  
  as delay a1, (8192+8192/2)/sr
  outs as, af1
endin

</CsInstruments>
<CsScore>
i1 0 20
</CsScore>
</CsoundSynthesizer>
```

**Comment by Oeyvind** [comment]
Oh, interesting. Thanks for looking into it. I understand it better now.
But wouldn't we expect the phases to go "back to normal" after unfreezing?

tir. 23. feb. 2021 kl. 18:09 skrev vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
I think the phase bias stays because it's just a fixed sine wave with regular interruptions. If this was a complex time varying spectrum, then we would not perceive any issues. It's just a byproduct of the phase vocoder integration. If you make the oscili glide in frequency, it should not have the smearing.

**Comment by Oeyvind** [comment]
I initially discovered it when freezing a live signal, and just made this
pulsed sine as a test to show the issue.

tir. 23. feb. 2021, 9:23 p.m. skrev vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
Definitely not an issue with pvsfreeze operation. It works as intended. Any issues of smearing are artefacts of the phase vocoder operation. This particular example will bring them out.

**Comment by Oeyvind** [comment]
Ok. So, to enable unfreezing without smearing, could one have a version of
pvsfreeze that keeps track of the phase changes that occur while frozen,
and this would allow us to get back to a clean unfrozen signal? (I am
asking mostly to verify that I understand the cause of the artifacts).

tir. 23. feb. 2021 kl. 23:23 skrev vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
Well, that means not freezing the frequency. The phase vocoder, despite its name, does not keep track of the phase at all. It produces the running phase by integrating the frequencies at the end. So the phase is the accumulation of all previous values of frequency in the signal. Once you freeze the frequency, when you restart at the resynthesis, you will have lost that "frozen" stretch. Freezing is kind of a non-standard operation anyway and it comes with no guarantees.
