### ISSUE TITLE
CsPerfThread Recording Issue

### ISSUE THREAD

**Issue by vlazzarini** [csound/csound#1503]
From Tarmo Johannes (@Tarmoj):

Hi!

As it came out debugging one issue by CsoundQt (that recording does not work any more with Csoun 6.16), seems that there is something in this commit that broke it:

https://github.com/csound/csound/commit/8ac630138219865fd452b8eaa44463f50d78dab2#diff-1de40d48e3a3126003edbb255f00e1662f7b314d517c5f446222b91ca2c830c0

I add a  c++ file for testing (and paste the code  below for any case).

Before that commit recording worked as expected, after that the result is a 44-byte file or so.

Please check if you get the same result and this is a bug?

Thanks!
tarmo

**Comment by vlazzarini** [comment]
@iskunk 
this has originated from your PR, would you be able to review it so we can have a full fix in the develop branch? I had to revert it for now so that functionality is restored, but it would be good to have your patch implemented. Thanks.

**Comment by iskunk** [comment]
Hi @vlazzarini,

Apologies for the delay. I had to re-establish my testing rig for Csound to look into this.

Using Git rev 69af4388, I am unable to reproduce the original leak in a `testPerfThread` run, which suggests that the issue may have been addressed by some other change since my PR.

(I did find a couple minor issues in `testIo`, which I'll get to you soon.)

I'll do a bit more Valgrind testing to check for anything else amiss in the test suite, but at least for this specific issue, it seems that there is nothing further to be done. I'll let you know if I find otherwise.

**Comment by tarmoj** [comment]
Hi!

Thanks! But does the recording by itsself work?

Tarmo

K, 4. august 2021 09:05 Daniel Richard G. ***@***.***>
kirjutas:

**Comment by iskunk** [comment]
Hello @tarmoj,

According to @vlazzarini's comment above, reverting the patch restored the recording functionality. You should be able to try the current code to verify that it is working.

(I can't say anything more about recording, as I was only addressing a memory leak visible in a test case.)

**Comment by vlazzarini** [comment]
memory leak not there, recording functionality restored.
