### ISSUE TITLE
krate string opcodes missing initialization

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1552]
It might look like some k-rate string opcodes somehow retain their state from previous initializations (??)

The csd below shows the problem. Running instr 1 should print the numbers in the string one by one. This happens correctly the first time the instrument runs, but it only prints 2 and 3 the second time the instrument runs.

As a test I have recreated the same procedure with i-time string opcodes in instr 2. This works every time. Sadly, I do need to make it work at k-rate...

```
<CsoundSynthesizer>
<CsOptions>
-n
</CsOptions>

<CsInstruments>

instr 1
  Snumbers = "1,2,3"
  Snumbers strcat Snumbers, ","
  kcomma strindexk Snumbers, ","
  while kcomma > -1 do
    Sval strsubk Snumbers, 0, kcomma
    kval strtodk Sval
    printk2 kval, 10
    Snumbers strsubk Snumbers, kcomma+1, -1
    kcomma strindexk Snumbers, ","
  od
endin

instr 2
  Snumbers = "1,2,3"
  Snumbers strcat Snumbers, ","
  icomma strindex Snumbers, ","
  while icomma > -1 do
    Sval strsub Snumbers, 0, icomma
    ival strtod Sval
    print ival
    Snumbers strsub Snumbers, icomma+1, -1
    icomma strindex Snumbers, ","
  od
endin

</CsInstruments>
<CsScore>
i1 0 .1 
i1 1 .1 

;i2 2 .1 
;i2 3 .1 

</CsScore>
</CsoundSynthesizer>

```

**Comment by vlazzarini** [comment]
There are two issues:
- The first issue is that the 'k' opcodes are being run at i-time. 

Because of that, when  they are run again strsub replaces the string at i-time (because the loop is non-op at i-time as the instrument does an i-pass).  Then the string passed at the top is then reduced to 2, 3. 

- The second issue is more subtle.  If there was no state remembered issue 1 would not make any difference. However, there is. The expression kcomma + 1 is translated into a synthetic k var (you don't see it), which retains the value. That's the state that is remembered. On the first run this is initialised to 0, on the second, it holds whatever value it had. When the opcode runs at i-time, the values will differ causing the effect you see.

To fix this, you need to explicitly create a variable to hold the sum and initialise it:

```
instr 1
  Snumbers = "1,2,3"
  kv init 0
  Snumbers strcat Snumbers, ","
  kcomma strindexk Snumbers, ","
  while kcomma > -1 do
    Sval strsubk Snumbers, 0, kcomma
    kval strtodk Sval
    printk2 kval, 10
    kv = kcomma + 1
    Snumbers strsubk Snumbers, kv, -1
    kcomma strindexk Snumbers, ","
  od
endin
```

**Comment by Oeyvind** [comment]
Oh. Thanks. I was unaware that it would create a synthetic k-var and that this would retain its value between instrument instances. Today's Csound lesson for me. Thanks again.

**Comment by vlazzarini** [comment]
if you run with -v you would see it. Any inline expression will do this (to compute its value).
