### ISSUE TITLE
Usage of hdf5read crashes the instrument at compile time

### ISSUE THREAD

**Issue by idranoels** [csound/csound#1577]
Hello everybody
I’m using Cabbage as a frontend for CSound and I’m trying to user hdf5write/hdf5read to save and restore datas to disk.
In a test file I have a line like this:
```

printks"before hdf5read:\n", 0
;        aArray[], aVar, kVar hdf5read "f:/mypath/src/cabbage/example.h5", "aArray*", "aVar", "kVar" ; Open hdf5 file and read variables
printks"after hdf5read:\n", 0

```

but if I remove the comment Cabbage suddenly crashes without printing anything before, so it should be a compile time issue.
The same issue occurs when I use CSound standalone.

I’m running under the following SW stack:

    Windows 10
    CSound 6.16 (double samples) Jul 17 2021
    Cabbage 2.8.0

I attach:

- CSound instrument [test_3.csd.txt](https://github.com/csound/csound/files/7952195/test_3.csd.txt)
- CSound output [test_3.txt](https://github.com/csound/csound/files/7952173/test_3.txt)
- Windows Event Viewer crash [EventViewer.txt](https://github.com/csound/csound/files/7952174/EventViewer.txt)

Thank you in advance

Sergio

**Comment by vlazzarini** [comment]
This code is not part of the Csound repository. It is part of the plugins repository. Can you open the ticket there?

Just note that there isn't anyone actively committed to maintaining that repository at the moment, so it may take a while to be looked at.

I am closing this here because we can't do anything about codd that is not part of the Csound repository.
