### ISSUE TITLE
Assignment from S-array at k-rate fails

### ISSUE THREAD

**Issue by mesca** [csound/csound#1586]
Assigning a variable from a S-array at k-rate results in an empty string:

```csound-document
<CsoundSynthesizer>
<CsOptions>
-n
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr Test
    S_arr[] init 1
    S_arr[0] = "foobar"
    k_index = 0
    S_txt = S_arr[k_index]
    printks("A: [%s]\n", 0, S_txt)              ; KO
    printks("B: [%s]\n", 0, S_arr[k_index])     ; OK
endin

</CsInstruments>
<CsScore>

i "Test" 0 .01

</CsScore>
</CsoundSynthesizer>
```

With 6.17, the output is: 
```
A: [foobar]
B: [foobar]
```

With 7.0, we have: 
```
A: []
B: [foobar]
```

Maybe or maybe not related to #1585.

**Comment by vlazzarini** [comment]
looks like wrong opcode is picked (i vs k). Will investigate.

**Comment by vlazzarini** [comment]
Ok, so the issue is that in 7.0 there's extra code being synthesised which is not needed:

```
##array_get.K args:	#S1	S_arr	k_index
=.S args:	S_txt	#S1
printks args:	"A: [%s]\n"	0	S_txt
```
whereas in 6.x we have just

```
##array_get.K args:	S_txt	S_arr	k_index
printks args:	"A: [%s]\n"	0	S_txt
```

I need to find why the extra code is generated, fix it and make sure other things do not get broken while I do it.

**Comment by vlazzarini** [comment]
My solution to this is to leave the expression expansion code alone as it seems to be fine tuned to parser3 and allow string assignment at both i and k-rate. Perhaps not ideal but it restores the functionality in these situations. This means that all string assignments will run both at init and perf time even if the assignment is at i-time only.

Maybe we will need to implement a thread flag in strings because that ambiguity has caused enough trouble since string types were hacked into the code without proper thought. I'll open a ticket for it.

**Comment by mesca** [comment]
Thanks for the fix.
