### ISSUE TITLE
Problem installing on xubuntu 20.04

### ISSUE THREAD

**Issue by giapat** [csound/csound#1591]
when installing `sudo make install`
 library 'libcsound64.so.7.0' is not copied to '/ lib' 
```
csound: error while loading shared libraries: libcsound64.so.7.0: cannot open shared object file: No such file or directory
```

**Comment by vlazzarini** [comment]
What's your `CMAKE_INSTALL_PREFIX`? I'm not convinced this is an error with the install script, because others have installed it without any problems.

Note that you are building Csound 7.0, which is in development, maybe it's not what you want. If you want to build the production Csound, check out the csound6 or master branches.
