### ISSUE TITLE
arrays in cs7

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1597]
```
--Csound version 7.0 (double samples) Mar  4 2022
[commit: be64ded13e7d3eccf9bbdf588cbc839a55a7b791]
```

```csound

instr 1
  kA[] fillarray 1, 2, 3, 4
  kB[] = kA * 2   ; the same happends if kB was inited before
  printarray kA
  printarray kB
  turnoff
endin

```
should print 

```
1 2 3 4
2 4 6 8
```

but prints

```
1 2 3 4
0 0 0 0
```

For any operation of the form `kA[] = ...` or `kA[] <op>= ...` where kA is an array, declared previous or not

**Comment by vlazzarini** [comment]
No wonder, kB 

```
fillarray.k args:	kA	1	2	3	4
##mul.[i args:	#k0[]	kA	2
=.generic args:	kB	#k0[]
printarray args:	kA	-1
printarray args:	kB	-1
```

and the entry for `=.generic`

```
../Engine/entry1.c:  { "=.generic", S(ASSIGN), 0,1, ".", ".", (SUBR)copyVarGeneric, NULL, NULL},
```

no wonder kB zero since it only runs at i-time. The generated code is wrong.

**Comment by vlazzarini** [comment]
So  I noticed that the "generic" assignment entry was put in recently in commit 0619302e62 and that was causing the parser to select it instead of a k-rate assignment. The types for it are given as "." and because they match all, they were also matching k-rate array expressions. A thread-1 opcode cannot be "match-all". I changed this to "i" input in 61986c0db030aac98d2ed46b311dff4a7abc97a2  which fixes the error reported and probably fixes all the other cases too. 

I am not sure why this entry was added, but it looks wrong anyway, maybe it can be removed altogether.

**Comment by kunstmusik** [comment]
This was from a commit 7 years ago and was part of the original design for
dealing with structs and arrays:

https://github.com//csound/csound/commit/b55b422b3c95784e238609304cb922b6943e01d1

I don't think the solution to set to "i" in OENTRY is a proper fix and does
not address issues of ambiguities of data type vs. processing rates.

**Comment by vlazzarini** [comment]
Ok, so we need a proper fix because if the code is reverted, it will be broken again.
