### ISSUE TITLE
BaBo direct parameter not in use?

### ISSUE THREAD

**Issue by OlaFosheimGrostad** [csound/csound#1602]
I cannot find the direct parameter being used? (not tested, found during refactoring, using refactoring tool)
https://github.com/csound/csound/blob/95007834d8afc68b9ae465a6f65b93b23ae41709/Opcodes/babo.c#L734

I think this line should be multiplied with the direct coefficient somehow:
https://github.com/csound/csound/blob/95007834d8afc68b9ae465a6f65b93b23ae41709/Opcodes/babo.c#L386

**Comment by vlazzarini** [comment]
One of the issues here is that this code has been around for a long time and the author is not in the community, so it's hard to say what's right or not. If we make a change to make that multiplication, it will change behaviour and possibly break people's code. 

My suggestion would be to leave it as is and make sure the manual is updated to note that the direct parameter is non-op.

**Comment by vlazzarini** [comment]
My worry is that someone has used a non-zero direct parameter and if that code is run with the changes then the result will not be as before.

**Comment by Oeyvind** [comment]
I agree very much about the concern for backwards compatibility. But also,
if something is clearly wrong, we should be able to remedy the error?

This manner of breaking backwards compatibility has happened to me earlier
at least. I do not remember the details, but IIRC it was some filter that I
had tweaked in my orchestra so that it produced my desired output (at the
time I did not really know what I was doing, so I merely changed things
around until it sounded good), then the code was fixed so that the filter
behaved correctly, which broke my instruments. When I raised the issue, I
got feedback that it just had to be fixed because the old behaviour was
clearly wrong.

I am not insisting how we handle it, but I think it would be good to settle
on a policy that ensures it is handled the same way in each case. Our
common understanding of backwards compatibility is very valuable, and cases
like this could open an opportunity to discuss details of how we relate to
it in each case. Then we can document this common understanding and
re-apply for new cases.

In the case of a parameter not having any effect on the output, I think it
is reasonable to assume that a user would not apply that parameter, and we
could allow ourselves to fix it so that it has the assumed behaviour. It
would be best if the original author did it, but if that is not possible, I
think we could be allowed to change it.

all best
Øyvind




tir. 31. mai 2022 kl. 22:17 skrev vlazzarini ***@***.***>:

**Comment by tjingboem** [comment]
I can imagine having a remark in the manual about a change in the code (cs7), and to add for older code where this opcode was used, to set the 7th parameter of _ifno_ to 0 for backwards compatibility.
Zero should turn down the direct signal.

We could then use this parameter to actually make the direct signal active?

And provide a nice second example for this updated babo opcode.

**Comment by kunstmusik** [comment]
I'm of the mindset that we go with a babo2 for this, considering the could cause a drastic audible change for legacy users of babo.

In regards to @Oeyvind's point, I think it's important we iron this out. I think we've stuck to the goal to protect users' works as best as possible, but it's not so black and white sometimes. New versions of older opcodes makes sense to me when we need to alter behavior, whether for a fix or change of feature. (Same as bumping major version in semantic versioning of software.)

**Comment by vlazzarini** [comment]
Ok, sounds good to me. I'm doing this (develop branch) and will report back

**Comment by vlazzarini** [comment]
babo2 is now added to develop branch and the manual updated
