### ISSUE TITLE
should init be able to copy i-arrays to k-arrays?

### ISSUE THREAD

**Issue by tomara-x** [csound/csound#1607]
so `kArr[] init iArr` would do exactly as `kArr[] = iArr` but at the init pass only, leaving the k-array free for manipuation (with = it gets recopied in k-time)

**Comment by johannphilippe** [comment]
I had the same issue recently and ended up doing 
```
	kchord[] init isize
	icnt init 0
	while icnt < isize do
		kchord[icnt] init iinp[icnt]
		icnt += 1
	od 
```
Which could elegantly be replaced by `kchord[] init iinp` but didn't work in this particular case, when you want to copy an array just at the init pass.

**Comment by vlazzarini** [comment]
```
kArr[] init iArr
```

will only work if iArr is a scalar variable (not an array). Otherwise it is a syntax error.
The meaning of 'init' to arrays is different to scalar variables. It means "create an array with a given size". If you want to create and initialise it, use `filarray`

Aside from that, note that k-rate assignment only takes place at perf time.

k.. init ...  is a init time expression
k.. =  ...   is a perf-time expression

So for example,

```
k1 init 10
print i(k1) // prints 10
```

```
k1 = 10
print i(k1) // prints 0 (if the instrument is a new allocation)
```

I am closing this because there's no issue reported. Please subscribe to the email list or join a forum to ask questions like this.
