### ISSUE TITLE
Windows detects a threat in 6.18 installer

### ISSUE THREAD

**Issue by giovannibedetti** [csound/csound#1644]
Trojan:Script/Wacatac.B!ml
This program is dangerous and executes commands from an attacker.
![image](https://user-images.githubusercontent.com/1912983/198224465-f9ec6fc2-4411-43df-8355-708387d1a709.png)

**Comment by vlazzarini** [comment]
@stekyne why is this happening with a github actions-built installer?

**Comment by stekyne** [comment]
It seems like it's a common false positive. It just describes a generic trojan rather than a specific variant. I can't say I've seen it on my own system though. We can possibly submit the installer for review by MS: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide#part-4-submit-a-file-for-analysis. You can add the installer name to an exclusion list if it is blocking you from installing.

**Comment by vlazzarini** [comment]
Also there's a binary release package, which should have no issue (no installer used).

**Comment by stekyne** [comment]
@vlazzarini which installer did you take for the release? I tried downloading/installing various ones from the past week and it seems like 1 in particular is throwing this error. `Csound6_x64-6.18.0.1199-windows-x64-installer.zip` seems to work fine but `Csound6_x64-6.18.0.1198-windows-x64-installer.zip` doesn't.

**Comment by DaveSeidel** [comment]
I had the same issue with build 1198.

**Comment by vlazzarini** [comment]
I don't know which, but I think it was the latest in the csound6 branch. Could you replace the installer then? I have no way to tell which is good. Just make sure the released name is the same so it doesn't break the link.

**Comment by stekyne** [comment]
It seems this installer is not being flagged as malicious anymore and working fine. We can ignore this issue now. If it happens again, we may just have to wait for a period when Windows defender doesn't flag it.

**Comment by vlazzarini** [comment]
thanks @stekyne
