### ISSUE TITLE
String pfields in the score cause p1 to be set to 0 in the instrument

### ISSUE THREAD

**Issue by gogins** [csound/csound#1686]
The attached minimum reproducible example demonstrates the bug.

Whenever the score has a string pfield, it seems that the p1 pfield in the instrument definition is set to 0, which in turn makes the nstrstr opcode return a blank string. The position of the string pfield does not matter.

Using "%s" and "strget" in the string format field does not seem to fix this behavior.

[string-pfield-test.txt](https://github.com/csound/csound/files/10366773/string-pfield-test.txt)

**Comment by gogins** [comment]
This is on a MacBook Pro M1 running Ventura 13.1.

I tested with Csound 6.18 for arm64 installed using Homebrew, _and_ with the Csound 6.18 universal binary installed from the GitHub release page.

Both binaries produced identical results.

**Comment by vlazzarini** [comment]
The issue seems to be here:

https://github.com/csound/csound/blob/master/Engine/namedins.c#:~:text=MYFLT%20%20named_instr_find_in_engine(CSOUND,ENGINE_STATE%20*engineState)

This function is called in insert() (insert.c) and is returning 0 for p1. I think this is because it is called without a named p1, and so it can't find the name and can't return the correct p1. My impression is that it should not be called in this case, but I have not written the code so maybe @jpffitch  can check this.

My current fix which in view of the above might not be the final one is to check if the returned p1 is 0 and not use that, keeping the original p1. This was done in the csound6 branch. Once we agree on the correct fix, then we can apply this to develop as well.

I think this problem may have been introduced when fractional named p1 values were introduced.

**Comment by jpffitch** [comment]
#Thar loos like te answer. my cange for tagged naed instryent was mis 
writtn

Dos your change fix it al#/  Sirr aving local problemsat present

**Comment by vlazzarini** [comment]
I don't know if it fixes for all cases, but it does for Mike's example.

Do you have another example where it's broken?
