### ISSUE TITLE
k() in cs7 not working as in cs6

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1697]
for sending a constant value, say 1, to a k-channel in csound 6, i had to use k(1).
this is not any more working in cs7 develop (--Csound version 7.0 (double samples) Mar  9 2023, [commit: 2503fc0b439f70973a6ee9fdd810fda6d111882c]).

the csd below returns this error:

> error:  error: opcode 'k' for expression with arg types cS not found, line 14
> from file test.csd (1)
> error:  Unable to find opcode entry for 'chnset' with matching argument types:
> Found:
>  (null) chnset @
> Candidates:
>   chnset.i iS
>   chnset.k kS
>   chnset.a aS
>   chnset.S SS

in my opinion, it would be good to have both possibilities as legal, either
  chnset 1, "bla"
or
  chnset k(1), "bla"

```csound
<CsoundSynthesizer>
<CsOptions>
-o dac
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 64
nchnls = 2
0dbfs = 1

chn_k "bla",2

instr 1
 chnset k(1), "bla"
endin

</CsInstruments>
<CsScore>
i 1 0 1
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
This seems to be a bug in the parser, 

```
error: error: opcode 'k' for expression with arg types cS not found, line 14
```

this indicates that the parser is reading both 1 and "bla" as arguments to k.

I tested with  `a1 oscil k(1), 100` and that did not give trouble.

**Comment by scottsitar** [comment]
This looks like it is caused by a shift/reduce conflict caused by these two productions:

```
expr: '(' expr ')'
expr_list: expr
```

While parsing the statement in instr 1, we reach a state in the parser where:

- top of parse stack: `'(' expr`
- lookahead token: `')'`

The current cs7 behaviour is the parser decides to shift here, leading to `(1)` being interpreted as an expr (and losing the knowledge that this came from a parenthesized expression), so I'm not sure we'd be able to fix this in `convert_statement_to_opcall()` since we wouldn't know which part of the expr_list was originally inside the parentheses.  I think we really want the parser to reduce here, and when I trace through what would happen in that case, it correctly reduces down to a function_call and continues as desired.  I haven't thought through what other consequences this might have, though - it's just what would make this specific example work.

I think this might have something to do with the fact that cs7 will allow variable names to shadow opcode names.  Specifically, the cs6 parser is able to avoid this conflict because when it parses this line, the chnset token gets type T_OPCODE0, and so the parser then knows the rest of the line is expressions.  The cs7 parser tries to hold off on making that call, resulting in two valid ways to interpret this line:

```
chnset     k(1), "bla"   ; opcode = chnset, args = k(1), "bla"
chnset     k       (1), "bla"   ; out_arg = chnset, opcode = k, args = (1), "bla"
```

This also explains why your oscil example didn't show the same behaviour, because the "a1" token removed the conflict on how to interpret oscil, which removed the conflict on how to interpret k(1).

In terms of desired behaviour and not breaking existing projects, maybe we could aim to have the parser always interpret it as the first of the two options above (the reduce case for the parser state), but then if that doesn't make sense, try to expand it out into the second option in `convert_statement_to_opcall()`?  That way, we won't lose the fact that there were parentheses, and we'd be able to ensure we did a correct transformation on the tree.

**Comment by vlazzarini** [comment]
sounds reasonable, what do you reckon @kunstmusik ?

**Comment by kunstmusik** [comment]
@scottsitar thanks for investigating this problem! It's been a while since I've looked at this area of the codebase so I'll need to review further to understand all the details. (I thought this scenario was originally handled in early CS7 code, so I want to check if this is a regression or was just never handled correctly.)

**Comment by scottsitar** [comment]
I'm happy to do the commit binary search to see if I can spot a regression.  Goodness knows I could use the git practice, haha.

I've been playing around with some grammar modifications to see if I could get it going, but I always seem to break parenthesized expressions in weird and wonderful ways in my attempts so far.  I've noticed the cs6 parser had another trick up its sleeve - alongside the tokens T_OPCODE and T_OPCODE0, there were tokens T_OPCODEB and T_OPCODE0B which were exactly the same except they ended with a left parenthesis (and ate whitespace).  This let the parser prioritize the starts of potential function calls over things that would match `'(' expr ')'`.

**Comment by scottsitar** [comment]
Best I can tell, the change in behaviour to what we're seeing now happened very early in the develop branch, in this commit:

https://github.com/csound/csound/commit/ce62c05fa

I get a very clear error message about the arg types for the 'k' opcode in that commit, but not in any other commit to the start of the branch.

**Comment by kunstmusik** [comment]
Thanks for researching that @scottsitar, guess this has been a longstanding issue. Also apologies for slow responses, been occupied with some non-Csound things. One thing to note is there is another issue I'm investigating regarding operator precedence with complex expressions that seems off in CS7. I've got some PRs to review and want to get the wasm build working again, then will return to this issue.

**Comment by scottsitar** [comment]
No worries!  I'm squeezing this in between work and kids as well.  In the meantime, I've been looking through other issues to keep getting more familiar with things and seeing what I can reproduce locally.

**Comment by vlazzarini** [comment]
Restarting this discussion as I want to see if we can fix this before the conference next week. I agree with @scottsitar's analysis. I checked and 

```
chnset(k(1), "bla")
```

parses correctly as the `( )` resolves the ambiguity. Still have not found an obvious route out of this.

**Comment by vlazzarini** [comment]
So I pinned this down to one specific statement case:

```
opcode   opcode(arg), arg
```

That is, an opcode without any inputs in the original syntax, taking as a first argument
another opcode inline with a single argument, followed by other arguments.

For example.

```
 out sin(aph), aph
```

```
chnset cspsmidinn(1), "bla"
```

I was able to insert a rule for opcall that successfully parsed this. Unfortunately, it broke other cases. So I think this needs someone with more abilities in bison that I have.

**Comment by scottsitar** [comment]
How would you feel about reintroducing tokens similar to T_OPCODEB and T_IDENTB?  It looks like in cs6 the only way to make a valid function call was to have no whitespace between the name of the function and the opening parenthesis.  It looks like the only way to make a valid function call in cs7 is by either a T_TYPED_IDENT or a T_IDENT token followed by '(', so if there were T_TYPED_IDENTB and T_IDENTB tokens, that would be enough to simulate having the parser reduce where we want it to reduce above.  Given that, though, there is one production I'm not sure would be okay with this, and that's the `opcall => out_arg_list '(' ')' NEWLINE` production.  I haven't fully understood what cases that will cover, but I suspect it could be modified to work as well.

**Comment by vlazzarini** [comment]
I wonder if that will not interfere with the parsing of variables in statements such as `var op args`. 

To me it seems like we should have a means of detecting that the parentheses are matched in `op  op(x), args` and get a funcall from the second `op`. But what do I know?

**Comment by scottsitar** [comment]
I've put together a quick PR (not for immediate review, but more of a suggestion for a path forward) reintroducing tokens that eat left parentheses:

https://github.com/csound/csound/pull/1953

It looks like it might be close?  There are only 2 csdtests failures - one having to do with an if statement, and the other having to do with a UDO.  The problematic csd file in the issue itself now parses correctly.
