### ISSUE TITLE
CSound fails to compile due to wrong SndFile library version

### ISSUE THREAD

**Issue by jacobhartzell** [csound/csound#1709]
I'm trying to compile CSound on Windows 10.  I have tried on both develop and master branches.

I run the command "cmake -B build -S . -DUSE_VCPKG=1" as per the instructions. 

I get the following output:

CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package):
  Could not find a configuration file for package "SndFile" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    C:/Users/Jacob/Documents/csound/git/csound/build/vcpkg_installed/x64-windows-csound/share/SndFile/SndFileConfig.cmake, version: 1.1.0 (64bit)

Call Stack (most recent call first):
  CMakeLists.txt:471 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by jacobhartzell** [comment]
Fails on csound6 branch as well. Probably a setup problem, but there's no way to just emaill support, hence bug ticket.

**Comment by vlazzarini** [comment]
I don't know anything about windows, but built artefacts are available from github. You don't need to build it yourself. 

This is the latest 6.19 beta

https://github.com/csound/csound/actions/runs/4865336500

7.0 beta is under the develop branch

**Comment by jacobhartzell** [comment]
I'm trying to develop my own opcodes, hence trying to build it myself.

**Comment by rorywalsh** [comment]
I think this is one for our @stekyne..

**Comment by gogins** [comment]
It should be possible to develop new opcodes in C or C++ for use with
Csound, without having to build Csound itself. Most opcodes don't need to
link with the Csound shared library, so all they need is to find the Csound
header files (csound.h or csound.hpp). Then you need to put your new opcode
shared library where Csound can find it; the easiest way to do this is to
simply add the path where the opcode library is built to your OPCODE6DIR64
environment variable.

Try to avoid 3rd party dependencies, and if you need them anyway, make sure
they don't conflict with those used by Csound itself.

It should be possible to put all your code in one .c or .cpp file, not use
a header file at all, and compile your opcode using a shell script or .bat
file instead of a makefile or CMake or something. This is what I do myself.
But if you're going to target Risset the plugin manager, then use CMake.

Feel free to ask more questions.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
what @gogins said. There is no need to build from sources to develop your own opcodes. All you need is the header files that come with an installation. Also emphasising what hd said, plugin opcodes are not linked to the Csound library.  Headers are all you need.

**Comment by stekyne** [comment]
Doesn't seem like the CI is broken. I've updated VCPKG to the latest version incase some of the URLs are out of date or something. #1710

**Comment by jacobhartzell** [comment]
Thanks for all the help. I was able to compile and play a custom opcode. Closing ticket.
