### ISSUE TITLE
Cmake find module for ALL optional dependencies?

### ISSUE THREAD

**Issue by bramtayl** [csound/csound#1726]
I'm trying to make a vcpkg port (https://github.com/microsoft/vcpkg/pull/32701) and vcpkg wants to avoid all optional dependencies. There are a few actual find modules, which are easy to disable, but there seem to be a ton of dependencies where pieces are found only via `find_library` or `find_executable` or something similar. If these were all find modules it would help with vcpkg and it would make the code easier to maintain probably.

**Comment by stekyne** [comment]
Hi thanks for working on this. It's true ideally all external dependencies would be found with find_package and abstracted out to `Find_x.cmake` files. Right now I'm cautious of doing that to avoid regression and build breakages for older builds for Linux/OSX. So keeping the status quo for those platforms. I have added a `USE_VCPKG` flag which is used crossplatform to build Csound using VCPKG as the package manager. All `Find_x.cmake` modules are provided by VCPKG in this scenario. 

I'm not sure how exactly it should be but there is a manifest.json in the root dir that lists Csound as a port. Can this be used instead of this custom one you have written? I think if you add some feature flags, you should either add all the Cmake options for modules or else just default to building it all. The csound build in this repo is mostly just the core but there are some small opcodes that have no dependencies also included. I would just build them by default and remove the flag option. We may also do this in the cmake file just to simplify it.

I also think you shouldn't need all of those patches or else they should be added as PRs to this repo instead of in VCPKG. It will be tough to maintain so many patches as time goes on. I'm also not really sure why they are needed? It's a bit risky to change the Cmake files with them and some of the source.
