### ISSUE TITLE
Option to disable installing the python bit

### ISSUE THREAD

**Issue by bramtayl** [csound/csound#1728]
Which seems to require sudo access

**Comment by jwaldmann** [comment]
seems to work on develop, but how can I use this with 6.18.1? 

```
cmake .. -DCMAKE_INSTALL_PREFIX=<somewhere> -DINSTALL_PYTHON_INTERFACE=OFF
make
...
CMake Error at interfaces/cmake_install.cmake:110 (file):
  file cannot create directory: /usr/local/lib/python3.11/dist-packages.
  Maybe need administrative privileges.
```

NB -  my current work-around is to manually delete lines 96 (to end) of `interfaces/cmake_install.cmake` before `make install`


perhaps I can use develop (7.0?) instead of 6.18 - but I need to build csound-plugins as well (I want FLTK) and that does not seem to work, but perhaps that error is unrelated.

**Comment by kunstmusik** [comment]
Closing out this issue as PRs addressing it were merged. 

@jwaldmann: Is this still an issue that you will need a fix? We're trying to direct our attention to CS7 development now and if you need a fix for csound6 maybe best to open a new issue and add a reference to this one and we can address it there.
