### ISSUE TITLE
Refactor API for standard types

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#1890]
https://github.com/csound/csound/pull/1852 introduced exposing of csound's standard variable types via CSOUND struct. I think there's an opportunity to make this a little tidier than adding all of the types to the CSOUND struct, perhaps using a sub struct. Adding this issue to further investigate.

**Comment by vlazzarini** [comment]
@kunstmusik I pushed a new branch containing a refactor. The main idea is

- A struct containing standard type pointers (`CS_STANDARD_TYPES`)
- A pointer to this struct added to `CSOUND` replacing the individual type pointers
- A single module API function `GetType()` to return a type given a type name char (a, k, etc)

This tidies up the way we expose types and also should allow us to add new types to the interface
without breaking backward ABI compatibility.

It may be possible to extend the refactor further, but I think it would now be mostly to do with internal changes, so it may be pushed to a later date.

**Comment by kunstmusik** [comment]
Seems like GetType and csoundGetTypeWithVarTypeName() should be merged and only one used (preferring the latter). csoundGetTypeWithVarTypeName() is an ugly long name, but it works better IMO since it takes in char* and works for all type names.

**Comment by vlazzarini** [comment]
I'll look at it right away.

**Comment by vlazzarini** [comment]
So that looks much neater, it was a great suggestion.
I  made GetType an interface to GetTypeWith... to avoid having to expose the internal typePool.

**Comment by vlazzarini** [comment]
I think this is completed now. In the end, following your suggestions, we did not need to expose the types via the API anymore since we have them in the the typePool and can access them easily through GetType(). This also led me to move the standard types header to the internal headers directory since none of it needs to be exposed via the API: the add standard types is only used internally and the const types themselves can be obtained via csoundGetTypeWithVarTypeName().

**Comment by vlazzarini** [comment]
I've added access to the typePool so that the type system functions can be useful in the API. If this is a bit dangerous we should make it const and remove the add functions from the API.

Now we have to decide about varPool functions:

```
  PUBLIC CS_VAR_POOL* csoundCreateVarPool(CSOUND* csound);
  PUBLIC void csoundFreeVarPool(CSOUND* csound, CS_VAR_POOL* pool);
  PUBLIC char* getVarSimpleName(CSOUND* csound, const char* name);
  PUBLIC CS_VARIABLE* csoundFindVariableWithName(CSOUND* csound,
                                                 CS_VAR_POOL* pool,
                                                 const char* name);
  PUBLIC int csoundAddVariable(CSOUND* csound, CS_VAR_POOL* pool,
                               CS_VARIABLE* var);
  PUBLIC void recalculateVarPoolMemory(CSOUND* csound, CS_VAR_POOL* pool);
  PUBLIC void reallocateVarPoolMemory(CSOUND* csound, CS_VAR_POOL* pool);
  PUBLIC void initializeVarPool(CSOUND* csound, MYFLT* memBlock, CS_VAR_POOL* pool);
```

Does it make sense to keep them in the API? If so, we should provide means of access to the varPools for them to be useful.

**Comment by kunstmusik** [comment]
@vlazzarini Could you set this branch up as a PR so I can review the code? 

I think csoundFindVariableWithName might be useful if someone wanted to implement a debugger (to read global and local variable values). The rest might be interesting for people doing low-level instrument/UDO assembly, but I'd be surprised if they got used by anyone.

**Comment by vlazzarini** [comment]
Will do. 

So should we expose the CSOUND varPools somehow?
