### ISSUE TITLE
(Anonymous) array expressions that do nothing with printarray at least 

### ISSUE THREAD

**Issue by eleses** [csound/csound#1902]
This is a somewhat undocumented feature, but it's possible to not size the arrays before calling `fillaray` (due to how the internal C function tabinit works):

```
gi[] fillarray 4,5,6,7
printarray gi
```
That works fine (and `lenarray(gi)` also has the expected value). The following "anonymous array expression" is also accepted by the (Csound 6) parser though:

```
printarray(fillarray(4, 5, 6))
```

But it does absolutely nothing (observable). It is a bit odd because

```
printf_i "??Len %d", 1, lenarray(fillarray(4, 5, 6))
```
does work as expected, and prints a length of 3, but I'm not sure if the internal state is fully consistent. The parser rejects something like `(fillarray(4, 5, 6))[1]` so I don't know what's actually stored in the anonymous array.

I think I know what the problem is:

```
opcode p2nd, 0, i[]
    iA[] xin
    printf_i "2nd elem: %d", 1, iA[1]
endop

p2nd fillarray(4, 5, 6)
```

This actually complains that it `Found: (null) p2nd k[]`, so the anonymous `fillarray` generates a k-array, but I'm still not sure why `printarray` doesn't print it. I'm guessing because I was running it in instrument 0. Trying `p2nd(fillarray:i(4, 5, 6))` to force it to use the i-version complains that `Found: (null) p2nd @`, which I'm not sure what it means.

**Comment by vlazzarini** [comment]
I cannot see the issue here. 

```
printf_i "??Len %d", 1, lenarray(fillarray(4, 5, 6))
```

this is doing exactly what the semantics of the code asks for, create an array and take its length.  Nothing else is asked from it. The code `(fillarray(4, 5, 6))[1]` is currently not syntactical. 

Note that

1 - Yes, the function-syntax version fillarray() produces a k[]. The opcode `printarray` takes a k-rate array.
2 - There is no current way to ask for a different overload in this case, but the new parser will eventually allow it (it is a known limitation). The semantics `fillarray:i(...)` asks for an i-rate variable as output rather an array output (`i[]`) and so the code does not parse.
3 - You can use this code (in Csound 7)

```
opcode p2nd, 0, i[]
    iA[] xin
    printf_i "2nd elem: %d", 1, iA[1]
endop

instr 1
iArr[] = fillarray:i[(4, 5, 6)
p2nd iArr
endin
```

Matters such as these are best discussed in the Csound list. We reserve the issue tracker for bugs and other improvement requests.
