### ISSUE TITLE
OSC receive behaviour: user error, or buffer clutter?

### ISSUE THREAD

**Issue by tremblap** [csound/csound#1927]
Dear all

I'm a re-newbie in Csound, discovering all the new features since I left it in 1996 :) I hope this 'unexpected behaviour' report is more a problem on my side, so please take this as a candid nudge and tell me I'm wrong (and where!)

At the moment, I struggle to get OSC to work as smoothly as in Max, SC and Pd. I went on the forum, got some help, but I cannot get the same number of messages per second treated as I get in Protokol and SC.

It is probably simpler to read the last 2 posts of this thread, in which I give the thruput I get in various settings, including 3 OSCreceives or an instance of OSCraw. In the first case, I get at best half the thruput, and in the latter, I get 620 messages per second of noise.

I'm happy to help troubleshoot and forward any test code, obviously!

**Comment by Oeyvind** [comment]
Hi tremblap,

I can not see the previous messages here (on email), but the throughput
might be related to your ksmps(?)
The opcode is called each ksmps period, but not in between. If there are
multiple messages in the buffer, you would usually read iteratively until
you reach the most recent one (processing only the most recent one).

all best
Øyvind

man. 26. aug. 2024 kl. 15:32 skrev tremblap ***@***.***>:

**Comment by tremblap** [comment]
Sorry the thread is here: 
https://forum.csound.com/t/osclisten-updating-global-k-rate-variables-seems-to-clog/1772/10

ksmps is 64 so at 44k I should be fine to get a lot more than I do...

**Comment by tremblap** [comment]
Posting the code here, to archive:

Tetsuya Miwa's sending code to test (got good reception of this in SC for instance)
```
<CsoundSynthesizer>
<CsLicense>
</CsLicense>
<CsOptions>
-m 128 -odac
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 64
nchnls = 2
0dbfs = 1

instr 1
kx[] init 10
ky[] init 10
iport = 7773

kx[0] = jitter:k(0.5,1,2)+0.5
kx[1] = jitter:k(0.5,1,10)+0.5
kx[2] = jitter:k(0.5,0.1,2)+0.5
kx[3] = jitter:k(0.5,0.1,0.5)+0.5
kx[4] = randomh:k(0,1,1)
kx[5] = randomh:k(0,1,5)
kx[6] = phasor:k(0.1)
kx[7] = phasor:k(0.5)
kx[8] = phasor:k(1)
kx[9] = phasor:k(5)

ky = 1-kx

OSCsend kx[0], "localhost", iport, "/sb3/mb/x", "ffffffffff", kx[0],kx[1],kx[2],kx[3],kx[4],kx[5],kx[6],kx[7],kx[8],kx[9]
OSCsend ky[0], "localhost", iport, "/sb3/mb/y", "ffffffffff", ky[0],ky[1],ky[2],ky[3],ky[4],ky[5],ky[6],ky[7],ky[8],ky[9]
endin
</CsInstruments>
<CsScore>
i1 0 10000
</CsScore>
</CsoundSynthesizer>
```

My test code. Comment like 50 or 51 to select the receiving instrument:

```
<CsoundSynthesizer>

<CsOptions>
-m 128
-odac
</CsOptions>

<CsInstruments>
; Initialize the global variables. 
ksmps = 64
nchnls = 2
0dbfs = 1

gkcount init 0

instr   ReceiveOSC
  iPort OSCinit 7773
  kx[] init 10
  ky[] init 10
  kz[] init 10
  kk1 init 0
  kk2 init 0
  kk3 init 0

  nxtmsg:
    kk1, kx OSClisten iPort, "/sb3/mb/x", "ffffffffff"
    kk2, ky OSClisten iPort, "/sb3/mb/y", "ffffffffff"
    kk3, kz OSClisten iPort, "/sb3/mb/z", "ffffffffff"
    if ((kk1 == 0) && (kk2 == 0) && (kk2 == 0)) goto ex
    ; printks "count: %d x: %f y: %f\\n", 0.04, kcount, kx[0], ky[0]
    gkcount = gkcount + 1
    kgoto nxtmsg
  ex:
endin

instr ReceiveAll
Smess[] init 100
top:
Smess,ka OSCraw 7773
kn = 0
while kn < ka do
  ; printf ": %s ", kn+1, Smess[kn]
  kn += 1
od
printf "%d items\n", ka, kn
gkcount = gkcount + 1
if ka > 0 kgoto top
endin

instr PeriodicPrinter
  ; schedule("ReceiveOSC", 0, 10000)
  schedule("ReceiveAll", 0, 10000)
  kmax init 0
  kTrig metro 1
  printf "count: %d messages. Max so far: %d m/s\n", kTrig, gkcount, kmax
  kLate delayk kTrig, 0.1
  if kLate == 1 then
    kmax max kmax, gkcount
    gkcount = 0
  endif
endin

schedule("PeriodicPrinter", 0, 10000)

</CsInstruments>

<CsScore>
</CsScore>

</CsoundSynthesizer>
```

The first receiver stalls at about half the speed of SC, and the 2nd seem to get a steady 620 messages per second to service even without anything on port 7773 (according to Protokol et al). I am puzzled by both results. Again, most probably it is my Csound understanding of how to service this. Below is the same receiving code in SC.

```
(
~nbms = 0;
~max = 0;

OSCdef(\ballX, {~nbms = ~nbms + 1}, "/sb3/mb/x", recvPort:  7773);
OSCdef(\ballY, {~nbms = ~nbms + 1}, "/sb3/mb/y", recvPort:  7773);
OSCdef(\ballZ, {~nbms = ~nbms + 1}, "/sb3/mb/z", recvPort:  7773);

Routine{
	{
		~max = ~nbms.max(~max);
		"% items in the last second. % max so far\n".postf(~nbms, ~max);
		~nbms = 0;
		1.wait;
	}.loop;
}.play
)
```

**Comment by vlazzarini** [comment]
A few things:

1) OSCinit should be placed outside instruments to ensure it is run once and before anything else

2) OSCraw is used as means of picking data without having to specify what it is. Is akin to sniffing. It is not designed for standard OSC communcations. @Oeyvind can explain its rationale, it was designed for some of his applications

Csound uses liblo for OSCinit/OSClisten so if there is any slow down, it may be due to this library behaviour. 

@Oeyvind have you noted any issues (beyond those we addressed by reimplementing OSCsend?) If liblo is misbehaving we may have to consider rolling our own, but given the pressures to finish Csound 7, that will be further down the line.

**Comment by tremblap** [comment]
Hello Prof Lazzarini, long time no speak!

If you think I should try the same code in Csound 7 on my machine, if that helps and that is not reproducible on your end, let me know, I'm happy to help.

**Comment by vlazzarini** [comment]
Ignoring OSCraw, which I don't think is relevant here,  I've collected the code from above into a single CSD and run it. 

```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>

<CsInstruments>
; Initialize the global variables. 
ksmps = 64
nchnls = 2
0dbfs = 1

gkcount init 0
giPort OSCinit 7773

instr 1

  kx[] init 10
  ky[] init 10
  kz[] init 10
  kk1 init 0
  kk2 init 0
  kk3 init 0

  nxtmsg:
    kk1, kx OSClisten giPort, "/sb3/mb/x", "ffffffffff"
    kk2, ky OSClisten giPort, "/sb3/mb/y", "ffffffffff"
    kk3, kz OSClisten giPort, "/sb3/mb/z", "ffffffffff"
    if ((kk1 == 0) && (kk2 == 0) && (kk2 == 0)) kgoto ex
    gkcount = gkcount + 1
    kgoto nxtmsg
  ex:
endin

instr 2
  schedule(1, 0, -1)
  kmax init 0
  kTrig metro 1
  printf "count: %d messages. Max so far: %d m/s\n", kTrig, gkcount, kmax
  kLate delayk kTrig, 0.1
  if kLate == 1 then
    kmax max kmax, gkcount
    gkcount = 0
  endif
endin

schedule(2, 0, -1)

instr 3
kx[] init 10
ky[] init 10
iport = 7773

kx[0] = jitter:k(0.5,1,2)+0.5
kx[1] = jitter:k(0.5,1,10)+0.5
kx[2] = jitter:k(0.5,0.1,2)+0.5
kx[3] = jitter:k(0.5,0.1,0.5)+0.5
kx[4] = randomh:k(0,1,1)
kx[5] = randomh:k(0,1,5)
kx[6] = phasor:k(0.1)
kx[7] = phasor:k(0.5)
kx[8] = phasor:k(1)
kx[9] = phasor:k(5)

ky = 1-kx

OSCsend kx[0], "localhost", iport, "/sb3/mb/x", "ffffffffff", kx[0],kx[1],kx[2],kx[3],kx[4],kx[5],kx[6],kx[7],kx[8],kx[9]
OSCsend ky[0], "localhost", iport, "/sb3/mb/y", "ffffffffff", ky[0],ky[1],ky[2],ky[3],ky[4],ky[5],ky[6],ky[7],ky[8],ky[9]
endin

schedule(3, 0, -1)

</CsInstruments>
<CsScore>
</CsScore>
</CsoundSynthesizer>
```

Not quite sure what are the expected results, but this is is what I get:

```
count: 0 messages. Max so far: 0 m/s
count: 615 messages. Max so far: 56 m/s
count: 638 messages. Max so far: 675 m/s
count: 635 messages. Max so far: 697 m/s
count: 591 messages. Max so far: 699 m/s
count: 603 messages. Max so far: 699 m/s
count: 607 messages. Max so far: 699 m/s
count: 623 messages. Max so far: 699 m/s
count: 588 messages. Max so far: 699 m/s
count: 603 messages. Max so far: 699 m/s
count: 614 messages. Max so far: 699 m/s
count: 623 messages. Max so far: 699 m/s
```

If I don't run instr 3, I get no messages as expected.

**Comment by tremblap** [comment]
Running the instr 3 and my receiving code in SC I get:

```
0 items in the last second. 0 max so far
1408 items in the last second. 1408 max so far
1344 items in the last second. 1408 max so far
1408 items in the last second. 1408 max so far
1344 items in the last second. 1408 max so far
1408 items in the last second. 1408 max so far
1344 items in the last second. 1408 max so far
```

and in Protokol I get similar numbers (around 1400 m/s).  So the OSCsend implementation works as expected, but there is something in the parsing of OSCreceive it seems.

**Comment by vlazzarini** [comment]
The number of messages is how many OSCsend can put out (due to ksmps). If I run it in a different csound process with ksmps = 16, and listen to it using the code above I get

```
count: 0 messages. Max so far: 1435 m/s
count: 63 messages. Max so far: 1435 m/s
count: 2617 messages. Max so far: 1435 m/s
count: 2377 messages. Max so far: 2809 m/s
count: 2542 messages. Max so far: 2809 m/s
count: 2545 messages. Max so far: 2813 m/s
count: 2367 messages. Max so far: 2813 m/s
count: 2371 messages. Max so far: 2813 m/s
count: 2617 messages. Max so far: 2813 m/s
count: 2552 messages. Max so far: 2881 m/s
count: 2312 messages. Max so far: 2881 m/s
count: 2304 messages. Max so far: 2881 m/s
count: 2623 messages. Max so far: 2881 m/s
count: 2624 messages. Max so far: 2881 m/s
count: 2368 messages. Max so far: 2881 m/s
count: 2559 messages. Max so far: 2881 m/s
count: 2554 messages. Max so far: 2881 m/s
count: 2381 messages. Max so far: 2881 m/s
```

**Comment by tremblap** [comment]
I have a hypothesis. I can reproduce the same results in SC by ignoring mb/x and mb/y. So maybe the triple OSClistener scenario is where it stalls - either in my code with the triple conditional (which is how I understand we must purge the OSC input stack) or deeper in the code.

**Comment by tremblap** [comment]
Indeed the problem doesn't seem to be OSCsend - the same send code is being received in SC and Protokol 3 times as fast. If I run the send code at ksmp=16 I get in SC:

```
4321 items in the last second. 4321 max so far
5533 items in the last second. 5533 max so far
5632 items in the last second. 5632 max so far
5632 items in the last second. 5632 max so far
5486 items in the last second. 5632 max so far
```

**Comment by vlazzarini** [comment]
I think it's the counting. I replaced the line

```
    gkcount = gkcount + kk1 + kk2 + kk3
```

and now I am getting

```
count: 0 messages. Max so far: 0 m/s
count: 1238 messages. Max so far: 107 m/s
count: 1253 messages. Max so far: 1390 m/s
count: 1181 messages. Max so far: 1390 m/s
count: 1275 messages. Max so far: 1390 m/s
```

twice the original number.

**Comment by tremblap** [comment]
oh this opens a great can of worm in my understanding of how the osc stack is purged (and where I should action the values).

Here is a commented bit of code that might explain how I understand it from the docs. It is most probably my error:

```
nxtmsg: ;this is run every kr as a FIFO stack of OSC messages
    kk1, kx OSClisten giPort, "/sb3/mb/x", "ffffffffff" ; this takes x if it is the next in the stack
    kk2, ky OSClisten giPort, "/sb3/mb/y", "ffffffffff" ; this takes y if it is the next in the stack 
    kk3, kz OSClisten giPort, "/sb3/mb/z", "ffffffffff" ; this takes z if it is next in the stack
    if ((kk1 == 0) && (kk2 == 0) && (kk2 == 0)) kgoto ex ; this checks that one of the listener has produced something
    gkcount = gkcount + 1 ; this is where I action stuff (expecting a single OSC message to have been updated)
    kgoto nxtmsg ; this goes to the next element in the stack
  ex: ; this is where we go once the stack of that KR is purged
```

now, if the listeners search the stack for the next valid message (x y or z) in each loop, that would explain parts of my problem.

**Comment by vlazzarini** [comment]
you can always separate the checks for each listener in separate loops if that's what you need.

```
  kk1 = 1
  while kk1 != 0 do
    kk1, kx OSClisten giPort, "/sb3/mb/x", "ffffffffff"
    gkcount = gkcount + 1
  od
  kk2 = 1
  while kk2 != 0 do
    kk2, ky OSClisten giPort, "/sb3/mb/y", "ffffffffff"
    gkcount = gkcount + 1
  od
```

**Comment by Oeyvind** [comment]
Hi,

Just chiming in, re the OSCraw question.
The reason I asked for OSCraw to be made was to be able to "learn" the
address of a message where the address is unknown. This was originally used
to assign Csound-generated modulation data to any control parameter in a
DAW. The DAW (Reaper in my case) sends out the OSC address of any GUI
control when you touch it, so it was convenient to interrogate this message
stream to auto-learn assignments/mappings.

I think you could use OSCraw for regular OSC communication too, if you do
not mind parsing the messages yourself. As far as I can see, it should not
be (much) more expensive than OSClisten. However, for standard usage it is
generally more convenient to use OSClisten.

For your counting of messages, I get the same number of messages with both
OSCraw and OSClisten.
The ksmps of the receiving csd does not matter for the count, as the
message queue (network buffer) is read until empty.
Running the sender at ksmps=10, I get around 1680 messages/s, which is
significantly lower than the k-rate (should be able to get max 4410
messages at sr=44100, ksmps=10).
So, it seems something is slowing down OSC communication. I'm not sure if
it is the sending or receiving or both (read on).

For diagnostic purposes, I found it useful to have the sender and receiver
in separate csd's as it also enabled to use different k-rates for the two.
This enabled me to verify that I receive the same number of messages
regardless of ksmps in the receiver. Which also is a convincing argument
that the network buffer is read until empty. So it would be interesting to
know where the extra message counts in SC comes from.
Now, to compare these results with what you get in SC, I think you would
need to also inspect the data values received both by SC and Csound.
Just to eliminate potential doubles read by SC ...or something similar,
maybe it counts each message more than once? ... just guessing as I don't
know SC very well... your function call {~nbms = ~nbms + 1} is unfamiliar.
Perhaps you could take the time received for each message and also use that
for better debugging function (reaching far outside my competence here, so
bear with me, just thought I'd mention the idea) . It seems very odd that
you get more messages in SC, because both OSClisten and OSCraw will read
messages from the network buffer until it is empty

I did modify tremblap's receive slightly, pasted below.
I use Victor's counting with OSClisten, counting all of the kflags (kk1+kk2
etc)
I also commented out the third OSClisten (receiving kz, as there is nothing
sent on that address from the sender)
The OSCraw receiver was modified slightly, as it would count k-rate passes
rather than number of received messages. Now counting number of messages.
I tested this on Windows, so I also needed to change "localhost"
to "127.0.0.1" in the sender. For some reason localhost does not work on
Windows.


all best
Øyvind


<CsoundSynthesizer>

<CsOptions>
-m 128
-odac
</CsOptions>

<CsInstruments>
; Initialize the global variables.
ksmps = 10
nchnls = 2
0dbfs = 1

gkcount init 0

instr   ReceiveOSC
  iPort OSCinit 7773
  kx[] init 10
  ky[] init 10
  kz[] init 10
  kk1 init 0
  kk2 init 0
  kk3 init 0

  nxtmsg:
    kk1, kx OSClisten iPort, "/sb3/mb/x", "ffffffffff"
    kk2, ky OSClisten iPort, "/sb3/mb/y", "ffffffffff"
    ;kk3, kz OSClisten iPort, "/sb3/mb/z", "ffffffffff"
    if ((kk1 == 0) && (kk2 == 0) && (kk2 == 0)) goto ex
    ; printks "count: %d x: %f y: %f\\n", 0.04, kcount, kx[0], ky[0]
    gkcount = gkcount + kk1 + kk2
    kgoto nxtmsg
  ex:
endin

instr ReceiveAll
Smess[] init 100
top:
Smess,ka OSCraw 7773
if ka == 0 then
  kgoto skip
endif
kn = 0
while kn < ka do
  ;printf ": %s ", kn+1, Smess[kn]
  kn += 1
od
;printf "%d items\n", ka, kn
gkcount = gkcount + 1
kgoto top
skip:
endin

instr PeriodicPrinter
  ;schedule("ReceiveOSC", 0, 10000)
  schedule("ReceiveAll", 0, 10000)
  kmax init 0
  kTrig metro 1
  printf "count: %d messages. Max so far: %d m/s\n", kTrig, gkcount, kmax
  kLate delayk kTrig, 1/kr
  if kLate == 1 then
    kmax max kmax, gkcount
    gkcount = 0
  endif
endin

schedule("PeriodicPrinter", 0, 10000)

</CsInstruments>

<CsScore>
</CsScore>

</CsoundSynthesizer>






tir. 27. aug. 2024 kl. 16:48 skrev vlazzarini ***@***.***>:

**Comment by tremblap** [comment]
Thanks for this @Oeyvind - I can confirm that the sender is sending at full speed. It is one of the sources I test in all 3 receivers (SC, Protokol, and Csound), where I always get values lost in the latter vs the 2 former. The other source I use is my Lemur app (which spits out 240 m/s when I go crazy on the xy pad) and the best I get is still loosing a few packets.

With the csound sender code (me too in a different file and terminal) at 16 ksmp I get 5632 m/s in SC, and in Csound, 5100 m/s

**Comment by tremblap** [comment]
One last comment. When I send from SC with this code:
```
n = NetAddr("127.0.0.1", 7773);
o = Routine{{n.sendMsg("/sb3/mb/x".asSymbol, *10.collect{1.0.rand}); 0.001.wait}.loop}.play
```
I get 1km/s in both SC and Protokol, but I get 930, then 870 in Csound's receiving code. I changed the ksmps to no avail.

Now this is far from pressing and a big problem, but that might explain why in my original post I get more 'stairwell' sounds - if I lose packet, that would sound like it.

anyway, if that is not considered a bug, please close the issue, I'm sorry for the noise!

**Comment by Oeyvind** [comment]
Ah, yes, the Lemur can send a lot of data, especially if you use physics on
the XY pad balls (bouncing around).

When you get over 5000 messages per second, it could be good.... but also
raise the question if the counting is good(?). If you have an sr of 48k and
ksmps 16, I would assume the max number of messages would be 3000 (same as
the kr).
And, just to check the difference between SC and Csound, in one of your
test files you have

kLate delayk kTrig, 0.1

... and this is cutting the counting period short (you keep counting only
in 0.9 seconds)
If you do

kLate delayk kTrig, 1/kr

... you get as close to a whole second as you can get, and a slightly
higher message count

Looking at it again, you should probably better do
  if kTrig == 1 then
... rather than the delayed k-trig (kLate)

Øyvind

tir. 27. aug. 2024 kl. 21:49 skrev tremblap ***@***.***>:

**Comment by Oeyvind** [comment]
Do you use the

kLate delayk kTrig, 0.1

in that test?

tir. 27. aug. 2024 kl. 22:11 skrev tremblap ***@***.***>:

**Comment by tremblap** [comment]
I was, and now I use the recommended `if kTrig == 1 then` (which used to give me only 0 as if the print was done slower than the reset) and a ksmp of 16, and i get better values:
```
count: 1021 messages. Max so far: 1022 m/s
count: 930 messages. Max so far: 1022 m/s
count: 1021 messages. Max so far: 1022 m/s
count: 1022 messages. Max so far: 1022 m/s
```

and I can get up to 5 times as much.

Now, this is good news that it seems that my understanding was bad in term of what is serviced when and that is no bug. Sorry for the noise... and thanks for the support.

**Comment by vlazzarini** [comment]
No problem, thanks to @Oeyvind for chiming in.

This also spurred me to implement our own internal OSC input, so we don't need to depend on liblo. We have an UDP server so all I have to do is to parse the messages and stick them somewhere. This is done now, should be merged soon into develop.

**Comment by tremblap** [comment]
Happy to roadtest if needs be. I'm bad at csound, but I'm quite thorough at testing :)
