### ISSUE TITLE
Csound 6.18.1 package needs Rosetta

### ISSUE THREAD

**Issue by goncalogato** [csound/csound#2004]
Hello,

Csound 6.18.1 package is Universal but needs Rosetta. Is there going to be a truly Universal version?

Thank you so much.

**Comment by vlazzarini** [comment]
It doesn't need rosetta, afaik. I can run the csound program here on arm64 on my M1 Mac.

**Comment by vlazzarini** [comment]
![image](https://github.com/user-attachments/assets/8d24096b-5761-4d83-a57a-48b308ba1d9c)

**Comment by goncalogato** [comment]
Thank you. I think it's the installer that is requiring Rosetta....

**Comment by vlazzarini** [comment]
Then it may be because the installer was built on an Intel machine.
The installers for 7.0 beta are built by github  actions, but I don't know on what machines they were built, we cannot guarantee they are fat binaries.
You can check at the Actions tab. The latest artefacts build is here
https://github.com/csound/csound/actions/runs/11467272026

**Comment by goncalogato** [comment]
Thank you. Can a universal or ARM installer be built for Csound 6.18.1?

**Comment by vlazzarini** [comment]
Unfortunately, 6.x is EOL. We're not developing it anymore. It can be built from sources following the instructions in the repo.

**Comment by goncalogato** [comment]
OK, thank you. So I guess I hope Csound 7 arrives soon!

**Comment by vlazzarini** [comment]
you can download it already from the github actions artefacts.
