### ISSUE TITLE
Expression parsing issue

### ISSUE THREAD

**Issue by vlazzarini** [csound/csound#2013]
The expression 

```
(asig2+asig1)*kg + adel1
```

generates wrong code:

```
##add.aa args:	#a0	asig2	asig1
##add.ka args:	#a1	kg	adel1
##mul.aa args:	#a2	#a0	#a1
```
when we should have instead

```
##add.aa args:	#a0	asig2	asig1
##mul.ak args:	#a1	#a0	kg
##add.aa args:	#a2	#a1	adel1
```

Full code:

```
<CsoundSynthesizer>
<CsOptions>
-odac -iadc 
</CsOptions>
<CsInstruments>
0dbfs = 1
nchnls = 2

instr 1
asig1 inch 1
asig2 inch 2
kg = 1
adel1 delayr 1
      delayw  (asig2+asig1)*kg + adel1
      out adel1, adel1
endin

</CsInstruments>
<CsScore>
i1 0 z
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
Note that this error does not happen all the time, only when the expression is in the argument of an opcode without outargs and containing a single inarg,

```
instr 1
k1 = 1
k2 = 1
k3 = 2
k4 = 3
printk2 (k1+k2)*k3 + k4
endin
```

if we change this to

```
printk 0.5, (k1+k2)*k3 + k4
```

or if we assign it

```
kn = (k1+k2)*k3 + k4
printk2 kn
```

then the code is generated correctly. Notice that this is the case in the earlier example, where the delayw takes a single argument. If we replaced delayr/delayw by delay, the code would work as expected.

It may be related to #1697, since

```
printk2((k1+k2)*k3 + k4)
```
also works correctly (function syntax always generates the correct code).

The `(k1+k2)` seems to be the problem in the same way that `k(.)`  is a problem with opcodes having no outargs (e.g. chnget) and used in classic opcode syntax.

NB: changing the order of the operands so to move the `()` to the right also fixes it: `k4 + (k1+k2)*k3 `

**Comment by jpffitch** [comment]
On

⁣​


-------- Original Message --------
From: vlazzarini ***@***.***>
Sent: Tue Oct 29 19:04:52 GMT 2024
To: csound/csound ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [csound/csound] Expression parsing issue (Issue #2013)

The expression 

```
(asig2+asig1)*kg + adel1
```

generates wrong code:

```
##add.aa args:	#a0	asig2	asig1
##add.ka args:	#a1	kg	adel1
##mul.aa args:	#a2	#a0	#a1
```
when we should have instead

```
##add.aa args:	#a0	asig2	asig1
##mul.ak args:	#a1	#a0	kg
##add.aa args:	#a2	#a1	adel1
```

Full code:

```
<CsoundSynthesizer>
<CsOptions>
-odac -iadc 
</CsOptions>
<CsInstruments>
0dbfs = 1
nchnls = 2

instr 1
asig1 inch 1
asig2 inch 2
kg = 1
adel1 delayr 1
      delayw  (asig2+asig1)*kg + adel1
      out adel1, adel1
endin

</CsInstruments>
<CsScore>
i1 0 z
</CsScore>
</CsoundSynthesizer>
```


-- 
Reply to this email directly or view it on GitHub:
https://github.com/csound/csound/issues/2013

**Comment by scottsitar** [comment]
Very briefly, it looks like the parsing of printk2 (k1+k2)*k3 + k4 is going something like this:

    first printk2(k1+k2) gets reduced into a function_call (function = printk2, args = k1+k2)
    then the * is shifted onto the parser stack
    then each of k3, +, and k4 are shifted onto the parser stack (so, it seems like it's not getting the relative precedence of + and * correct here)
    then it reduces k3+k4 to an expr
    this leaves it with function_call * expr

Then, something happens which I don't understand yet (make_opcall_from_func_start(), I suppose?) which converts what it's got above:

printk2(k1+k2) * (k3 + k4)

into this:

printk2( (k1+k2) * (k3+k4) )

I haven't definitively found where in the code this happens yet, although I can certainly imagine what that transformation is trying to accomplish. But yes, at the root, there seem to be two issues:

    mistakenly reducing printk2(k1+k2) as a complete function call (cs6 gets this right because it insists on no spaces between the function name and the opening parenthesis)
    not recognizing the relative precedence of + and * during the middle of the parse (I suspect because of the opcall : function_call '*' expr_list production, so that it doesn't have enough context to properly apply the precedence rules)

**Comment by scottsitar** [comment]
Very briefly, it looks like the parsing of `printk2 (k1+k2)*k3 + k4` is going something like this:

- first printk2(k1+k2) gets reduced into a function_call (function = printk2, args = k1+k2)
- then the `*` is shifted onto the parser stack
- then each of k3, `+`, and k4 are shifted onto the parser stack (so, it seems like it's not getting the relative precedence of `+` and `*` correct here)
- then it reduces `k3+k4` to an expr
- this leaves it with `function_call * expr`

Then, something happens which I don't understand yet (`make_opcall_from_func_start()`, I suppose?) which converts what it's got above:

`printk2(k1+k2) * (k3 + k4)`

into this:

`printk2( (k1+k2) * (k3+k4) )`

I haven't definitively found where in the code this happens yet, although I can certainly imagine what that transformation is trying to accomplish.  But yes, at the root, there seem to be two issues:

- mistakenly reducing `printk2(k1+k2)` as a complete function call (cs6 gets this right because it insists on no spaces between the function name and the opening parenthesis)
- not recognizing the relative precedence of `+` and `*` during the middle of the parse (I suspect because of the `opcall : function_call '*' expr_list` production, so that it doesn't have enough context to properly apply the precedence rules)
