### ISSUE TITLE
Update Csound API to use TypeSystem for Channels

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#318]
We should review the current API for channels and add new functions for querying the type of channels.  This would use something like:

`CS_TYPE* csoundGetChannelType(CSOUND* csound, const char* channelName);`

We should look towards migrating towards using more generic channel functions in place of older type-specific ones.  We might do this by having the older functions delegate to the newer ones.  We should keep the older functions for backwards compatibility during the 6.xx series of Csound, though we might mark them deprecated and remove them in Csound 7.  

Also, instead of just removing older functions, we could create an additional backwards compatibility header that contains the older functions that delegate to the newer ones. That would allow older apps to easily compile with the newer API just by adding the backwards compatibility header.

**Comment by vlazzarini** [comment]
The Csound 7.0 API has been updated to allow access to a wider number of channel types. The access interface remains the same. However with structured types (string, fsig, arrays), opaque data structures are used with dedicated interfaces.

We could expose the types instead of the data structures, but I think that would be an extra complication with not that much more gain as each type still needs to be decoded in different ways (e.g. fsigs vs arrays vs strings). So we would have to add an interface to get the type data structure from CS_TYPE.

Also given the fact that we want to complete this work by mid September, I would suggest we keep this interface.

**Comment by vlazzarini** [comment]
So here's the status now:

- the channel interface has added support for arrays and improved support for fsigs
- the API still contains the original channel interface with minor modifications. These consist basically in exposing (void *) instead of (MYFL *) for channel data pointers.

My opinion is that we should not change the above, in particular we should note that channel types are the same as var types (CS_TYPE*), but there's a mapping from one to the other. Changing this might not be all that useful. So I have done this:

- Added a CS_TYPE *varType to the CHNENTRY structure, which is initialised on channel allocation
- Added an interface to it so the varType name can be exposed (as a const char *) (csound.h)
- Added an interface to it so the varType (as a const CS_TYPE *) (csound_type_system.h)

I think we should be good now. I am hoping this is enough for 7.0 and we can exploit this further in later versions of the API.
