### ISSUE TITLE
Compile Csound and csound~ for Windows 64 bit 

### ISSUE THREAD

**Issue by alfonso73** [csound/csound#333]
Hi,
Windows 64 bit systems need csound and csound~ !

thanks and all the best

a.

**Comment by gogins** [comment]
There is now a build system for creating a WIndows version of Csound for 64 bit CPU architecture (see issue ).

**Comment by alfonso73** [comment]
great news!!! thanks
Il 25/mar/2016 12:49, "Michael Gogins" <notifications@github.com> ha
scritto:

**Comment by gogins** [comment]
Please confirm that the current WIndows installer is usable for building csound~. If it is please close this issue. If not let me know here.

**Comment by alfonso73** [comment]
Hi Michael. Is the csound~ source VS ready? If yes i can try compiling in the next days.

**Comment by gogins** [comment]
I don't know. I've never built csound~. I'm just trying to make sure that
found itself is compatible. Try it and let me know if you have problems and
we'll work it out.

Regards,
Mike

**Comment by alfonso73** [comment]
Hi Mike, i've just downloaded latest Csound source there are no instruction on how to compile csound~ on Visual Studio. Can anyone point me in the right direction? Maybe Rory or Steven?
best

**Comment by rorywalsh** [comment]
Is there not already a version available for 64bit Windows:
>
> https://github.com/csound/csound/issues/628
We're still awaiting instructions on how they actually built it.

**Comment by gogins** [comment]
I have just looked at the build files. Because I have not tried to build
csound~ for Max myself, I hope somebody will correct me (Steven Yi, Rory
Wash?) if I am wrong.

It seems that csound/frontends/max_csound_tilde is a subproject of the
master Csound build system. These are based on CMake. In theory you could
build the extern using either MSYS2/mingw64 or Visual Studio.

When I run CMake to build Csound ir prints the following messages:

Not building csound~ for Max/MSP
MAX_SDK_ROOT is not defined.

This means, I think, that if you manually configure CMake to set the proper
value of MAX_SDK_ROOT, then CMake will generate makefiles to build the Max
extern. This is assuming you are using MSYS2/mingw64, not Visual Studio, as
your compiler. The Max extern should then be built along with the rest of
Csound. You might need to rename the extern with suffix .mxe64 not .mxe.

However, nobody has actually gotten this approach to work as far as I know.
That's probably because Cycling 74 does not currently support the
MSYS2/mingw64 toolchain. People have built the extern with mingw64 but it
doesn't work.

We do know that somebody has built the extern and it runs. Perhaps they
created their own Visual Studio project file by hand, that would not be
diffcult, Just start a DLL project for x64 and add all the files in
csound/frontends/max_csound_tile/src to the project. Tell Visual Studio
where to find the Csound headers and import library (csound64.lib), there
is one of these in the current Windows installer for Csound, and where to
find the Max SDK headers and libraries. Then fix up whatever goes wrong...
this will work only if the max_csound_tilde files link only to C functions
from Csound (I haven't checked but that would make sense).

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

On Thu, Jun 16, 2016 at 9:51 AM, Alfonso Santimone <notifications@github.com

**Comment by alfonso73** [comment]
Hi again and thanks Mike and Rory,
seems that here
https://github.com/csound/csound/issues/628
unriginal has compiled it. I just tried it and it works on my system.
I ask him if he can share the VS project.
best
