### ISSUE TITLE
srconv generates blocks of junk

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#458]
About 4450 samples of it followinf similar length of apparent correct output.
I think Erik's secret rabbit code is a better algorithm anyway..  Perhaps we should drop this srcomv?

**Comment by kunstmusik** [comment]
Sounds good to me to drop it. I think if we just have a note to direct
users to other tools, it will be fine.

**Comment by vlazzarini** [comment]
if we can use his code, we should do
it.

**Comment by gogins** [comment]
Of course, defer to src.

Regards,
Mike

**Comment by jpffitch** [comment]
Only drawback is another dependency.  I will see if I can produce a d=similar frontend to Erik's library, but not for 6.05

**Comment by vlazzarini** [comment]
Is it compatible with LGPL, or will we have to licence it separately?

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by jpffitch** [comment]
SRC is GPL not LGPL so there may be issues.  I think Erik takes a 
firm/strog interpretation, but IANAL and licences confuse me greatly.

If I write a standalone program that uses SRC it can be distributed as 
GPL.  Problems may arise if this is constituted as a utility inside 
csound.

**Comment by gogins** [comment]
If SRC is a library that is linked statically or dynamically with Csound,
then the combination is a "derivative work" that would conflict with SRC's
GPL.

If SRC is a program that is redistributed with Csound and that Csound uses
"exec" or some such to run, then the combination is not a "derivative work"
and this usage should not conflict with SRC's GPL. Csound would of course
have to make SRC's code available as part of Csound's adherence to SRC's
GPL. I personally think this could be done by including a license notice
and link to SRC's code repository in the Csound distribution. This comes
from: https://www.gnu.org/licenses/gpl-faq.html#MereAggregation.

But of course, SRC is in fact distributed as source for a library

Therefore, we would have to write a "shell" program that implements what we
need as a GPL program, and license that part of Csound under the GPL
instead of the LGPL. But then, we would be able to invoke our "shell" for
SRC from Csound and to distribute our "shell" and its code without
violating the SRC's GPL, as in the preceding paragraph.

Please note, I am not a lawyer. This reflects a personal understanding of
the issues after doing some reading and googling.

Parenthetically, I think the distinction between dynamic linking and
executing with exec or such is a bit arbitrary. But I do not wish to
belabor the point or to challenge Erik de Castro Lopo's interpretation of
the GPL.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by mantaraya36** [comment]
I would propose dropping it altogether. There was a time when you would
need this tool to come with Csound, but now it's easy to get better tools
available out there. We could mark the application as removed in the manual
pointing to SRC.

Cheers,
Andrés

**Comment by joachimheintz** [comment]
why not asking erik directly?
whatever he agrees, should be ok, and make us free from too much 
juristical questions, i hope.
i personally would be glad to see this working as a csound utility again.
	joachim


Am 23.04.2015 um 20:44 schrieb gogins:

**Comment by jpffitch** [comment]
I have written a replacement program src_conv which is GPL, wic mainly follows the same argument structure.  New program is in git now.

i would like assurance that csound utilities exec'ing this progra is permitted in GPL/LGPL structure.

**Comment by vlazzarini** [comment]
If the utility is loaded by Csound as a dynamic library, then Csound becomes GPL, as far as I understand it. If it is run as a separate process, then it is the case that Csound is only acting as a shell, then I suppose the licenses can be different.

**Comment by mantaraya36** [comment]
I would suggest dropping it altogether.

Cheers,
Andrés

**Comment by joachimheintz** [comment]
but there are people using it, who may not know about alternatives.  and 
perhaps the alternatives are not available at all platforms?

	joachim


Am 13.05.2015 um 15:08 schrieb Andres Cabrera:

**Comment by mantaraya36** [comment]
I'm not sure... My impression is that many of these additional tools are
very unknown and underutilized, but I may be wrong. If there are people
using them, it's worth the effort to maintain them.

A

**Comment by jpffitch** [comment]
I believe that te new utility works and covers te same options (nearly).  The srcnv utility now execs the new program.  One slight difference isrange of qualities and the default associated.

I am closing this for now
