### ISSUE TITLE
--realtime dropping events for temporal loop

### ISSUE THREAD

**Issue by ErrorThink** [csound/csound#518]
This CSD fails when setting the --realtime flag, and the second instrument has a zero or very short duration:
```
<CsoundSynthesizer>
<CsOptions>
-odac
--realtime  ;fails with this flag. Comment it out to hear repeated notes.
</CsOptions>

<CsInstruments>
sr = 44100
kr = 4410
ksmps = 10
nchnls = 2
0dbfs = 1

instr 1

ares vco2 0.1, 220

outs ares, ares

endin


instr 2

schedule 1, 0, 0.25 ;beep

schedule p1, 0.5, 0.001 ;temporal loop
endin
</CsInstruments>

<CsScore>
f0 10
i2 0 0.1
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
For the --realtime mode to work you need low latency and small buffer sizes, e.g. of the order 
-b32 -B128, otherwise: 1) initialisation might happen too late 2) timing jitter will happen as everything is driven by the audio callback timing. Here, initialisation is taking more than 1 millisecond to occur, and
then the note is dropped. I have played a bit with the code to see if I can relax the requirements, but that would mean more CPU use too, because of threads running idle. I will review this again before our next release.

If you want to use --realtime mode, you will need to reduce your buffer sizes to the minimum and
possibly make your second schedule line with a p3 bigger than 0.001 (0.002 should do it, but it will depend on your system).

**Comment by ErrorThink** [comment]
OK, fair enough. Does this mean though that more complex orchestras, with more initialisation calls (thus taking longer to initialise), might need longer and longer p3's for that schedule line? (I'm thinking of live coding scenario's).

**Comment by vlazzarini** [comment]
Not particularly, but if you doing some very heavy computation or loading big files into memory at i-time, then it might (I am thinking here of extreme cases).
In your particular case here a p3 of 0.001 or 1 does not really matter as there is no perf-time code, so the instrument is only doing init time. You should always use a p3 larger than 0.001. You can also put a turnoff at the end, so that it turns itself off in the first perf cycle after initialisation. 
The main thing about --realtime is that it is designed for tight low-latency. If you do not have that, then it should not be used. Also, it is not really necessary in the majority of cases. The usual Csound operation mode should be sufficient. The difference with --realtime is that if initialisation and a few other blocking operations take longer than necessary, then the events depending on these will arrive late. But the audio thread never gets blocked. It is still experimental, though, and I thank you for reporting these issues.
