### ISSUE TITLE
ADSRs retrigger even when referring to the same note in the score

### ISSUE THREAD

**Issue by aure** [csound/csound#527]
I could very well be misunderstanding how this should work, but if I start a note and change its parameters while keeping the note's number the same, I don't think the ADSE should retrigger each time I change a parameter, but it is.  

Here's a CSD file that demonstrates the issue in vanilla Csound:  It should just bend the current note, but you definitely hear  a new note.  Thanks!

<CsoundSynthesizer>

<CsOptions>
-o dac
</CsOptions>

<CsInstruments>
sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1

;---- Opcodes ----
kADSR madsr 0.5, 0.1, 0.5, 1, 0
aOut foscili kADSR, p4, 1, 1, 1, 1, -1
out aOut
endin

</CsInstruments>

<CsScore>
f 1 0 16384 10 1

i 1.00005 0 -2 700 
i 1.00005 2 -2 800 
i 1.00005 4 -2 900 
</CsScore>

</CsoundSynthesizer>

**Comment by adambmedia** [comment]
Correct way to bend notes via p-fields is as follows:
i 1.01 0 -2 700
i 1.01 1 2  800
i 1.01 2 3  900
which will give three different pitches instead of what you're getting now.  Then, i statements invoke an initialization pass of the instrument which is why you're getting the reset on the envolope. If you stick a linseg on any of the other foscil arguments it will also reset to the first value of the linseg on each of the "bend" score statements.

kADSR madsr 0.5, 0.1, 0.1, 1, 0
kcar linseg 1.1, 1.6, 1
aOut foscili kADSR, p4, kcar, 1, 1, 1, -1
out aOut

Also suggested in the csound manual:
"Notes being tied to previous instances of the same instrument, should skip most initialization by means of tigoto, except for the values entered in score. For example, all table reading opcodes in the instrument, should usually be skipped, as they store their phase internally."

**Comment by vlazzarini** [comment]
I don't think this is a bug, it is just how things work. There is a chapter in the Csound book about toief noted that explains how the mechanism works.

**Comment by vlazzarini** [comment]
tied notes, typing on a phone is awful.

**Comment by aure** [comment]
Yeah, the -1 in the phase got me the tied note behavior I wanted out of focili, but there's no corresponding thing in the adsr, as well maybe there shouldn't be.  Updating the note with durations breaks infinite hold of the note though.  Seems like the tigoto is the best alternative, thanks!
