### ISSUE TITLE
chnget:S() problem...

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#607]
Seems like it's not possible to use chnget:S() in the same way one can for k and a rate variables. The second line from the code below produces a syntax error.

```
kTest = chnget:k("NumbericalChannel")
STest = chnget:S("StringChannel")
```

**Comment by vlazzarini** [comment]
yes, that's because the parser looks for an opcode called "S" and it can't find it, then fails. This is quite independent of the actually semantic rule where we look for the type name. We need to change the parser expression to be more accurate. Meanwhile, I've added an "S" opcode that allows the parser to read this. In git.

**Comment by jpffitch** [comment]
Surely this should be partially dealt with in the lexer and has no need for an opcode

**Comment by vlazzarini** [comment]
yes, but currently the parser rule checks for an opcode. I did not want to start changing things so close to a release.

**Comment by rorywalsh** [comment]
Do you have details of how this opcode works or is this an internal opcode?

**Comment by vlazzarini** [comment]
you don't need to worry about it. It is just there to allow the syntax to work. So your case is now covered.

**Comment by rorywalsh** [comment]
Great. Thanks.
