### ISSUE TITLE
ADSR note too short?

### ISSUE THREAD

**Issue by hlolli** [csound/csound#608]
Not sure if this is something that I should make an issue for. But I just installed fresh csound from latest develop branch on a new computer I have, and few of my instruments using adsr stopped working due to new error saying: 
INIT ERROR in instr 1: length of ADSR note too short

Here's maybe a reproduceable code (note that the error starts as soon as the duration is less than 0.2)
```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 128
nchnls = 2
0dbfs = 1.0

instr 1
aoscil poscil 0.1, 200
aenv adsr 0.1, 0, 0.5, 0.1
outs aoscil*aenv, aoscil*aenv
endin

</CsInstruments>
<CsScore>
i 1 0 0.19
</CsScore>
</CsoundSynthesizer>
```

**Comment by rorywalsh** [comment]
The error makes sense considering your attack and decay times are more than
your note's duration, but I never like when updates break older instruments
that had been working fine. Your code is sitting between a rock and hard
place.

**Comment by hlolli** [comment]
Yes wow, I always assumed that adsr automatically scaled to p3 values. But then again I don't use it too often. Easy to fix this at least. But these updates to break backwards compatibility, but if it's for good reason, I would support it.

**Comment by Oeyvind** [comment]
It was me who reported the issue a while back, as I was experiencing a lot
of artifacts with envelopes on short notes. Several enveloping opcodes got
an overhaul, and indeed there was some discussion about the best way to
fix. I take it on me for advocating the init error in this case. The reason
being it would produce clicks due to truncated envelope stages when note
duration was shorter than the specified envelope duration. Rather than
erratic clicks in the audio output, I mean it is better for the user to get
notified that something is wrong, and that the error is the user specified
parameters. It would be possible to just print an error (and produce audio
with clicks) instead of deleting the note.

2016-03-08 21:36 GMT+01:00 Hlöðver Sigurðsson <notifications@github.com>:

> Yes wow, I always assumed that adsr automatically scaled to p3 values. But
> then again I don't use it too often. Easy to fix this at least. But these
> updates to break backwards compatibility, but if it's for good reason, I
> would support it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csound/csound/issues/608#issuecomment-193957304>.
>



-- 

Oeyvind Brandtsegg
Professor of Music Technology
NTNU
7491 Trondheim
Norway
Cell: +47 92 203 205

http://www.partikkelaudio.com/
http://soundcloud.com/brandtsegg
http://flyndresang.no/
http://soundcloud.com/t-emp

**Comment by hlolli** [comment]
Yes I think printing a warning would be the way to solve this, but Im bit glad that this error came tough, because I noticed that many times Im using the adsr incorrectly. A smart instrument design should be to have special envelope for very short note values. Just of curiousity, is there any envelope available in csound that takes all parameters of envelope calculated from p3 fields automatically (now of course Im thinking about typing less code in live performance).

**Comment by vlazzarini** [comment]
if you place your envelope on a table and read with an oscillator with frequency 1/p3, then it will scale up or down to your duration. I am closing this. Any discussion should be moved to #601, otherwise it is hard for us to keep track of the issue.
