### ISSUE TITLE
[Csound6~] missing/ Option not provided in installation

### ISSUE THREAD

**Issue by GETBUB** [csound/csound#641]
Hi!

I recently installed CSound6 and following the guide "CSound in PD", I attempted to manually select the various components, specifically: csoundapi~

However, I did NOT get those options... 

The options I got were : Full installation, Compact Installation, and Custom Installation...

the only components available to select from in any of the installation choices were: **Core Csound** and **Python features**

In the Csound in PD tutorial, there are vastly more components present to select from during installation.

_Csound6_x64 6.07.0 in Windows 8_
 
I can´t seem to find any info on someone suffering something similar..

Thoughts? 

Thank You!

ps: I have already checked to see if Csound6~.dll was installed anyway in the bin folder and it was not.

edit: added "of" after "any"

**Comment by joachimheintz** [comment]
this is a question about the windows installer, so i added the label and assigned to michael gogins.

i think you refer to this text:
http://floss.booktype.pro/csound/a-csound-in-pd/

would be good to mention it next time, as this is not the canonical manual, but a textbook about csound.

**Comment by GETBUB** [comment]
Ok! Thank you!!

**Comment by gogins** [comment]
This feature (the PD object) is not available for Csound on Windows built
for 64 bit CPU architecture. This is because PD itself does not fully
support the 64 bit CPU architecture with loadable objects at this time. You
can try the beta installer for Csound 6.07 which is still built for 32 bit
CPU architecture, download it here:
https://sourceforge.net/projects/csound/files/csound6/Csound6.06/Setup_Csound6_6.07.0beta2.exe/download.
Or you can use 6.06 and earlier versions.

We will be tracking this and will support PD again when they fully support
loadable objects for x64.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by joachimheintz** [comment]
thanks; i have added a note about this in the floss manual.
	joachim

**Comment by GETBUB** [comment]
Great..

Thank you both for your swift responses and informative responses!
