### ISSUE TITLE
PADsynth click when choosing square

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#656]
I get no sound, only a click when i set the Profile Shape to 2 = square

profile_shape -- Number specifying the shape of the bandwidth profile: 1 = Gaussian, 2 = square, and 3 = exponential

profile Gaussian and exponential work jsut fine

**Comment by gogins** [comment]
I fixed this bug. The code was incorrectly rounding the profile parameter to an int. The meaning of the profile parameter for a square profile shape is that first a Gaussian profile is computed, then if the amplitude of that profile at that frequency is less than the profile parameter, the amplitude is set to 0, otherwise it is set to 1; counter-intuitively, a smaller value of the profile parameter creates a wider profile, and a larger value creates a narrower profile.

**Comment by tjingboem** [comment]
The problem still exists.
I have taken the example from the manual, changed all the profiles to 2 (= square) and i still get a loud click. The gaussian and exponential profile work perfectly.

Here is the csd:
[padsynth_square.csd.txt](https://github.com/csound/csound/files/465590/padsynth_square.csd.txt)

**Comment by jpffitch** [comment]
After the click I see tat the scale is broke

table 102:     262144 points, scalemax  -nan
B  7.000 ..  9.000 T  9.000 TT  9.000 M:     0.00     0.00
new alloc for instr 2:
PadSynth with sine tone.
B  9.000 .. 11.000 T 11.000 TT 11.000 M:     0.00     0.00
PadSynth with sine tone.
B 11.000 .. 13.000 T 13.000 TT 13.000 M:     0.00     0.00

which suggests to me that table 102 has incorrect  values or isall zero or 
some such.  I think thetake is generated by padsynt gen

        gi_padsynth_1 ftgenonce 0, 0, gispec_len, "padsynth", ibasehz, p6, 
0.0, 1, 2,  1.0, 1

and p6 is 0.3 .  But I have no understanding of the code

**Comment by jpffitch** [comment]
Out of my depth but I tried tracing function "profile" and in square case always returned 0
It looks as if it switches when e^(x*x) is a; in example a is 1 so there is no real solution

**Comment by gogins** [comment]
You did not merge all my fixes. I have restored them.

**Comment by gogins** [comment]
No, there is still a problem...

**Comment by gogins** [comment]
Okay, try this. Not sure if it is what was intended but it does make a usable sound that is different from the other profiles.

**Comment by jpffitch** [comment]
1: The last change was no change in the case of a=1 which is the test case

2:  I still get silence and clicks only from "square" padsynth

Actually I have seen no change in the code in profile at any stage in the issue.  I am suspecting the removing the square case would be better!

**Comment by gogins** [comment]
Send me your test case then. It should not be removed.

I suspect you do not have the latest code, or perhaps you have another copy
of the plugin being loaded. I verified that my change is in develop head.
You should see these changes:

     case 2:
 -        // The parameter a is the value of the profile curve at which the
profile switches from 0 to 1 and from 1 to 0.
 -        y = std::exp(-(x * x * 1));
 -        if(y < a) {
 -            y = 0.0;
 +        // The idea is to take profile 1 and simply say y goes to 0 if
below a and to 1 if above a.
 +        y = std::exp(-(x * x * a));
 +        if (y < a) {
 +            y = 0;
          } else {
              y = 1;
          }

I just tested this on Ubuntu 16.04 with gcc 5.4. There are no clicks with
any value of a.

However, using a = 1 as a test case is not correct, at least not without
tuning the other parameters. Using a = 1 can cause buffer underruns and
nans. With a = .1 or a = .01 nice usable effects are produced.

I have now put in code to clamp a between 0.00001 and 0.99999, but there
are still problems with some combinations of parameters. I would prefer not
to change this any more because high values of a can be useful after
adjusting the bandwidth and amplitude.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
Using again th example from the manual but having set the profile to square, i get this result:
[square.ogg.zip](https://github.com/csound/csound/files/467974/square.ogg.zip)

I'm using Linux Mint 17.3 (based on Ubuntu 14.04)

**Comment by gogins** [comment]
Did you rebuild csound a few hours ago?

In any case, with a set to 1 it cannot work. Try setting a to .1 or
something like that.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by jpffitch** [comment]
With muc smaller values of a I get sound OK  9not to my taste).  Perhaps we need information in the manual about parameters.
