### ISSUE TITLE
Proper distribution package for csound~

### ISSUE THREAD

**Issue by ech2** [csound/csound#696]
Hi everyone!

Currently the `csound~` object is distributed as archives with a lonely binary object. This is bad because the archive doesn't contain help files and examples. I checked the `frontends/max_csound_tilde` directory and found all this stuff there. Also I found scripts which build `.msi` and `.pkg` installers which were deprecated in favor of [packages](https://docs.cycling74.com/max7/vignettes/packages). Max package is essentially a directory with defined structure, containing such subdirs as `extras`, `help`, etc. Having a proper package we can submit a package to the their repository, and users will be able to install `csound~` from the Max itself through the [package manager](https://cycling74.com/2015/12/14/introducing-the-max-package-manager/).

I checked how the build process is done, but unfortunately I don't know CMake well enough to make modifications that would collect all assets into proper places.

**Comment by rorywalsh** [comment]
The issue here is that the Cmake build for csound~ on Windows doesn't work
for 64bit, which is the default for Csound on Windows now. The current
binary, which does work for 64bit Csound was contributed by a github user
who failed to provide any instructions on how he created it. It's fine for
now but as soon as the next version of Csound is released we won't have a
new binary.

**Comment by kunstmusik** [comment]
csound~ shouldn't be affected by Csound releases as long as the binary
interface has not changed in a backwards incompatible way. There are shell
and .bat scripts in the frontends/max_csound_tilde folder for building the
installers that use CMake to build, but then handle packaging.  I would
look at modifying those scripts rather than the CMake part to deal with
packaging into a different format.

**Comment by rorywalsh** [comment]
Yes this is true. My bad, let's hope for no more API bumps for a while.

**Comment by oscii** [comment]
@kunstmusik, ah indeed there is a script. But anyway I'd suggest to drop installers in favour of new packages. I can handle this and submitting to the package repository --- if you don't mind! :)

**Comment by rorywalsh** [comment]
Not at all! Please feel free to go for it.

**Comment by kunstmusik** [comment]
@oscii yes please do go for it

**Comment by vlazzarini** [comment]
This is in the wrong place. I am closing it and moving to the Csound~ tracker.
