### ISSUE TITLE
Seg fault on Linux with this .csd

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#697]
One of Iain's Cabbage examples is crashing for me with the following backtrace:

`0  0x00007ffff58e602e  _int_malloc  /build/glibc-GKVZIf/glibc-2.23/malloc/malloc.c  3803
1  0x00007ffff58e834a  __libc_calloc  /build/glibc-GKVZIf/glibc-2.23/malloc/malloc.c  3237
2  0x00007ffff652da4c  mcalloc  /home/rory/sourcecode/cabbageaudio/csound/Engine/memalloc.c  113
3  0x00007ffff652a34e  instance  /home/rory/sourcecode/cabbageaudio/csound/Engine/insert.c  2103
4  0x00007ffff6522b61  insert  /home/rory/sourcecode/cabbageaudio/csound/Engine/insert.c  175
5  0x00007ffff6532ef4  process_score_event  /home/rory/sourcecode/cabbageaudio/csound/Engine/musmon.c  768
6  0x00007ffff65338ec  sensevents  /home/rory/sourcecode/cabbageaudio/csound/Engine/musmon.c  962
7  0x00007ffff66a54e1  csoundPerformKsmps  /home/rory/sourcecode/cabbageaudio/csound/Top/csound.c  1945
8  0x00000000005373a4  Csound::PerformKsmps  /usr/local/include/csound/csound.hpp  359` 

Running it with Csound from the command line also gives a segmentation fault. Looks like a memory issue. I've attached the file(with.txt extension). Any ideas?

[Micropolyphony.txt](https://github.com/csound/csound/files/465857/Micropolyphony.txt)

**Comment by jpffitch** [comment]
Not on a computer now but I would run under valgrind first.

**Comment by jpffitch** [comment]
Probably this

==2304== Invalid write of size 8
==2304==    at 0x4E7E7FA: gen41 (fgens.c:2195)
==2304==    by 0x4E7D63F: hfgens (fgens.c:282)
==2304==    by 0x4FC39A2: ftgen_ (ftgen.c:155)
==2304==    by 0x4FC39A2: ftgen (ftgen.c:165)
==2304==    by 0x4E87398: init0 (insert.c:64)
==2304==    by 0x4E90141: musmon (musmon.c:228)
==2304==    by 0x4FA4B5B: csoundStart (main.c:508)
==2304==    by 0x40153A: main (csound_main.c:316)
==2304==  Address 0x1a495588 is 0 bytes after a block of size 8,216 
alloc'd
==2304==    at 0x4C2B200: calloc (in 
/usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==2304==    by 0x4E8D547: mcalloc (memalloc.c:113)
==2304==    by 0x4E7BD15: ftalloc (fgens.c:2360)
==2304==    by 0x4E7D5D1: hfgens (fgens.c:268)
==2304==    by 0x4FC39A2: ftgen_ (ftgen.c:155)
==2304==    by 0x4FC39A2: ftgen (ftgen.c:165)
==2304==    by 0x4E87398: init0 (insert.c:64)
==2304==    by 0x4E90141: musmon (musmon.c:228)
==2304==    by 0x4FA4B5B: csoundStart (main.c:508)
==2304==    by 0x40153A: main (csound_main.c:316)
==2304==

O commad line otherwise nothing happens
Does it need midi?

**Comment by rorywalsh** [comment]
Ok, then it's probably a different issue with Cabbage. The csd file uses
"-n -+rtmidi=null -M0"

**Comment by jpffitch** [comment]
I think that is sufficient to break memory allocaion.
Actually I tink the lasr assignment is misguided

**Comment by jpffitch** [comment]
an you try with current git version?  I have a possible patc but do not ave cabbage

**Comment by rorywalsh** [comment]
Thanks John. I'll pull from git a little later today and try it out..

**Comment by rorywalsh** [comment]
Thanks John. Everything working fine now. I guess you can close this ;)
