### ISSUE TITLE
In realtime, sr should default to the system sr if sr is not specified

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#755]
If would be helpful to be able to specify that a given csd is to be run realtime at whatever the samplerate of the given backend at the moment is. With the current behaviour the workaround is first to ask csound what the samplerate is (with `--get-system-sr`), parse that output at the shell and then pass that number as `--samplerate=` and leave the `sr` global variable unset at the csd's header. 

What I propose is to change the behaviour of `sr` **only** for realtime so that, in absense of a global `sr` at the header or as a command line parameter, it defaults to whatever samplerate is being used for the given backend. For offline rendering `sr` would still default to 44100.

**Comment by genell** [comment]
I like this! It would specifically facilitate using Csound together with jack, since jack requires everything to use the sample rate of the jack server. 
As I easily get confused I would suggest a "reserved expression" for sr, such as
sr=sys 
to set it to system sample rate. That way it is easily seen in the csd. 
Referring to sr later in the csd code should of course translate to the system sample rate value.

**Comment by gesellkammer** [comment]
I like the idea of making the setting explicit. I don't know if sr can accept a string, but something like 0 could stand for "system samplerate".

**Comment by genell** [comment]
That would work too, but would really prefer a string to really point out the difference from a numerical value.
