### ISSUE TITLE
No polyphony when using subinstr in Csound 6.09

### ISSUE THREAD

**Issue by adamfreese** [csound/csound#779]
Minimal example code follows:

```
<CsoundSynthesizer>
<CsInstruments>

sr = 44100
kr = 4410
ksmps = 10
nchnls = 2
0dbfs = 1

instr 1
  iFreq = p4
  iAmp = 1/32
  aSig pluck iAmp, iFreq, iFreq, 0, 1
  outs aSig, aSig
endin

instr 2
  iFreq = p4
  aLeft, aRight subinstr 1, iFreq
  outs aLeft, aRight
endin

</CsInstruments>
<CsScore>

i2 0 8 240
i. 1 7 300
i. 2 6 360
i. 3 5 480

</CsScore>
</CsoundSynthesizer>
```

I compiled the score using csound from the command line. If I use i1 in the score instead of i2, this sounds as expected: each tone starts without interrupting the previous. If I use i2, then each tone stops when the next one starts. I noticed this after I built Csound 6.09 from source; it didn't occur when I was using 6.08. I'm running Csound from Linux. The output reports no errors and no warnings.

**Comment by vlazzarini** [comment]
I can confirm the problem. I wonder if it has to do with the changes in negative p3 etc.

**Comment by vlazzarini** [comment]
No, I think it has to do with the changes in the out opcode. I have replaced it in instr 1 by
a global variable and now I get all the instances:

```
<CsoundSynthesizer>
<CsInstruments>

sr = 44100
kr = 4410
ksmps = 10
nchnls = 2
0dbfs = 1

gaout init 0
instr 1
  iFreq = p4
  iAmp = 1/32
  aSig oscili iAmp, iFreq
  gaout +=  aSig
endin

instr 2
  iFreq = p4
  aLeft, aRight subinstr 1, iFreq
  outs gaout, gaout
endin

instr 3
   gaout = 0
endin

</CsInstruments>
<CsScore>

i2 0 8 240
i2 0 7 300
i2 0 6 360
i2 0 5 480
i3 0 10

</CsScore>
</CsoundSynthesizer>
```
@jpffitch could you have a look to see if you can find out what happened?
The relevant code for subinstr performance is in insert.c:1608 - 1699. There is a loop
calling all opcodes from the instrument and then copying the outputs (1683-90), where
I think the problem might lie, but not quite sure how the changes in 'out' have affected it.

**Comment by jpffitch** [comment]
That code looks at spout directly which was changed to non-interleaving. That might be the problem

**Comment by vlazzarini** [comment]
do you know how to fix it?

**Comment by jpffitch** [comment]
Not sure what it is trying to do.  I think it needs the incr fixing.

⁣Sent from TypeApp ​

**Comment by vlazzarini** [comment]
it reads spout and spout only contains the output of only one of the running instances of the instrument.

**Comment by vlazzarini** [comment]
I had a look again and because we're using csound->spraw, there is a need to redesign the output for subinstr.

**Comment by jpffitch** [comment]
I just do not know what lines of 1666 -- 1679 are doing with spout incr.

**Comment by vlazzarini** [comment]
Ok, let me try to do this. I'll call for help if I reach a dead end.

**Comment by jpffitch** [comment]
There may be a similar issue in userop1 and 2 also in insert.c

⁣Sent from TypeApp ​

**Comment by vlazzarini** [comment]
no, that code is not supposed to use spout.
I figured it out and fixed it (hopefully). I'll document it here for future reference.

1. Each instrument has its own spout pointer (CS_SPOUT) and it used to point to csound->spout.
2. Once we introduced csound->spraw, and point the out opcodes to it, CS_SPOUT was not being
used correctly. Code in subinstr() and in kperf() that depended on it was broken.
3. The fix was simply to point ip->spout to csound->spraw in csound.c and replace all csound->spraw in aops.c by CS_SPOUT.

In GIT now, passing my tests, but it's worth keeping an eye making sure it has not broken anything else (I don't think so).

**Comment by vlazzarini** [comment]
Btw, eventually, we might consider using the spout pointers to hold the instrument instance own output buffer rather than point to a shared one. Then csound->spraw can go and we can change the out functions in aops.c not to accummulate, and the make_interleave() function in csound.c can do that job, mixing all active instruments. I think that is probably a cleaner way of doing things, and we can get rid of csound->spoutactive too.

**Comment by jpffitch** [comment]
and I think that would remove the need for a lock  round out opcodes

**Comment by adamfreese** [comment]
The issue is fixed. Thanks!
