### ISSUE TITLE
Can't fix "Reading CSD failed...stopping" message!

### ISSUE THREAD

**Issue by santibogacz** [csound/csound#834]
A couple of weeks ago I installed the 0.9.4.1 version on Windows 8.1 Pro (I was up to then using an older version) and ever since I've been dealing with this problem. I can open the program, I can write code but every time I want to run it, the message "Reading CSD failed...stopping" appears. It happens to absolutely ALL my csd files (even the old ones). Tried changing files to other directories. Tried to run it both with the soundcard connected and disconnected. 
Does anybody know what I could do to solve it?!

**Comment by jpffitch** [comment]
Csound version?  How are you using Csound?  What is 0.9.4.1?

⁣Sent from TypeApp ​

**Comment by santibogacz** [comment]
Csound Qt 6.09.1 64 bit

**Comment by joachimheintz** [comment]
this is the wrong place to ask.  this is an issue tracker for csound, 
but your problem is related to csoundqt.  so:
- best place would be the csoundqt mailing list:
   https://sourceforge.net/projects/qutecsound/lists/qutecsound-users
- or the csoundqt issue tracker (although it is only read by the 
developers and not a user forum):
   https://github.com/CsoundQt/CsoundQt/issues
- also the csound mailing list could be helpful, as there are many 
windows users who also use csoundqt as frontend:
   https://listserv.heanet.ie/cgi-bin/wa?SUBED1=CSOUND&A=1
