### ISSUE TITLE
Look at Online Installers as Platform Managers

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#869]
As discussed at 4th International Csound Conference and on Csound User's mailing list here:

https://listserv.heanet.ie/cgi-bin/wa?A2=ind1710&L=CSOUND&P=123473

There was some interest to rework the installer for Windows and OSX to do auto-updating and installation of frontends separately from Csound core. There was some investigation into using QT Installer Framework:

http://doc.qt.io/qtinstallerframework/ifw-overview.html

I'm filing this issue so that we don't lose track of this.

**Comment by gsenna** [comment]
I can try designing the online installer before starting to work on the Csound course if we choose to go with the Qt Installer Framework. But we'll need Windows and OSX people to actually compile it (and maintain it) on the target platforms.

Besides Csound Core, CsoundQt, Cabbage and Blue, what other add-ons should there be?

We'll also need server(s) for hosting the installer's repository. Unfortunately, I don't have access to that.

**Comment by gogins** [comment]
Would these targets be built online, e.g. with Travis or AppVeyor? I have
no interest in maintaining any other way of build the installer.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gsenna** [comment]
Apparently it is possible to use Github releases and Travis and AppVeyor to complete the whole process. I had my doubts but the citra-emu project seems to be doing it. But they do have a different URL that allows the online installer to go into the right folder. Can we have:

http://repo.csound.com/CsoundCore/Csound_6.09.1.7z

resolve to 

https://github.com/csound/csound/releases/download/6.09.1/Csound_6.09.1.7z?

The other thing to consider is the frontend installers themselves. We need every frontend developer involved in this discussion.

**Comment by kunstmusik** [comment]
@gsenna I'm not sure we could have it resolve to that URL, but could maybe do some kind of redirect. Will redirects be enough?  

Regarding frontend installers: pinging @rorywalsh and @tarmoj

**Comment by rorywalsh** [comment]
Ping received loud and clear. Cabbage has its own installer for Windows and
OSX but can just as easily be extracted from a zip as it no longer sets any
environment variables or system paths.

**Comment by gsenna** [comment]
@rorywalsh Yes, Cabbage would be easy because I'm already familiar with it. The CsoundQt installer would be the thing to tackle for me.

@kunstmusik Unfortunately I don't think redirects would work because the installer tries to download a 7z file from inside a directory. The problem is Github Releases don't seem to allow directories. A hack could be made to the Qt installer or maybe edit the XML file with a post-script, but I'm not so fond of that idea. 

I think a web server that takes into account .htaccess files is what's needed. I'll keep thinking.

**Comment by tarmoj** [comment]
Hi, Guillermo,

It would be quite easy for me to prepare zip files for Windows and OSX;  
including a directory with binary and all dependencies (expect Csound) and 
OSX, pasically the application packaged into zip file.  In fact that would be 
easier than preparing independent installers.

Should I upload such versions for testing?
Or can  you have a look if such zip for Windows works OK:
https://github.com/CsoundQt/CsoundQt/releases/download/0.9.4/CsoundQt-0.9.4-win-mingw64.zip

Sorry, I have not dwelved into the QtInstaller problems. Is there anything I 
can do to prepare CsoundQt for it?

tarmo

**Comment by gsenna** [comment]
Hey @tarmoj, I'll check that zip. Right now there's no need for you to do much. Thanks!

What would you all think about having Travis and Appveyor building and triggering the update process? Would you all be comfortable letting the VMs create 7z files rather than a binary and letting the Qt installer perform the installation on each platform? Are there any other frontends or add-ons besides CsoundQt, Cabbage and Blue that we should be shipping? 

However it is, we need a server. It actually doesn't have to host anything, but just have a couple of empty folders with .htaccess files inside them for the redirection. With that in place, each project (core and frontends) can have its own deployment tool building, creating the 7z files, publishing the result through a Github Release and pushing a commit to its own Github repository with the updated Updates.xml file. 

Another thing to keep in mind, are we going to have only the latest stable release of each program available through the installer or all of them available? As long as there is a Github Release we can have them all. What about betas?

Cheers.

**Comment by gsenna** [comment]
Forget about the servers, there were only 2 files in the QtIFW that needed to be modified to allow hosting everything on Github. We can create another repository (CsoundInstaller?) and bake our own patched version. After that it's just a matter of configuring Travis and AppVeyor to publish the 7z files and also to push the updated XML file back to the repository.

**Comment by rorywalsh** [comment]
That's great. We should probably make a list of all front-ends that can be
added. I make it:
Blue,
Winxsound,
CsoundQT
CsoundVST,
Cabbage,
CsoundUnity
CtCsound
Csound~
CsoundAPI~
I'm probably missing something major?

On 5 Nov 2017 12:24 a.m., "gsenna" <notifications@github.com> wrote:

Forget about the servers, there were only 2 files in the QtIFW that needed
to be modified to allow hosting everything on Github. We can create another
repository (CsoundInstaller?) and bake our own patched version. After that
it's just a matter of configuring Travis and AppVeyor to publish the 7z
files and also to push the updated XML file back to the repository.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/csound/csound/issues/869#issuecomment-341939929>, or mute
the thread

**Comment by jpffitch** [comment]
Not major but winsound still exists.

**Comment by stekyne** [comment]
Any more progress on this?

Saw this today (https://bintray.com) and thought it could be useful for this proposed setup. It's free for OSS projects. Appveyor has support for for it too (https://www.appveyor.com/docs/deployment/bintray/). It would probably allow more control than using GitHub releases but slightly more work too.

**Comment by gsenna** [comment]
I'm still doing some work with the Qt Installer Framework. I think it will work. The only small drawback is that I'll probably need someone to build Qt and the QtIFW statically on Windows and Mac. I don't have access to those. But I hope that it will not be such a big issue as we already have people with Qt experience around here and for me on the Travis Vagrant Linux VM it was just a matter of running ./configure <options>, make and then qmake, make.

**Comment by kunstmusik** [comment]
Closing as out-of-date. Seems like this isn't going to happen as part of core Csound and if anyone takes it up it could be done as a separate project.
