### ISSUE TITLE
bad udo declaration should produce better error message

### ISSUE THREAD

**Issue by DaveSeidel** [csound/csound#947]
If a UDO is declared such that the declared inputs and/or outputs don't match the body of the UDO, no error is produced until the UDO is used. The error points to the point of invocation instead of to the opcode itself, and the text of the error is not very helpul.

For example, the attached file produces the following console output:
```
0dBFS level = 32768.0
--Csound version 6.11 (double samples) Apr  1 2018 
[commit: 539b00be039cae2e5def3645637b8c21253891e2]
libsndfile-1.0.27
UnifiedCSD:  opcode-test.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled

error: syntax error, unexpected T_OPCODE  (token "test_opcode") from file opcode-test.csd (1)
 line 18:
>>>  test_opcode <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.005s, CPU: 0.005s
```

[udo-test.csd.txt](https://github.com/csound/csound/files/1913030/udo-test.csd.txt)

**Comment by maurocsound** [comment]
It's true that your UDO has some errors inside its body, but it's equally true that the call syntax of this UDO from "instr 1" is wrong, because you defined that "test_opcode" should have 1 output and no input, but then you call it with a statement that doesn't have a variable to its left size... Unlike C/C++ languages, Csound doesn't permit this. If an opcode definition has an output, in the caller code you have to place a variable (to the left side of the opcode statement) to accomodate the returned value. 
So, Csound in this case gives priority to the error from the caller. 

Anyway I agree with you that the first error Csound should display is the discrepancy between the UDO definition of its type parameters and the "xin" declaration in its body.

**Comment by kunstmusik** [comment]
Scheduling for 7.0.0 as I think we should evaluate our error messages for the release.

**Comment by vlazzarini** [comment]
This had already been improved and I have added some extra messaging to the feature/messages branch
