### ISSUE TITLE
Syntax error with faustcompile in Windows using 6.11 for Shapes.py from Computer Music Instruments

### ISSUE THREAD

**Issue by jcaballi** [csound/csound#969]
I'm reading Computer Music Instruments by Victor Lazzarini. I'm attempting to run the first program in Appendix B, Shapes. It seems the program can't find faustcompile. When I run csound -z, it's not there. I'm running Csound on Windows.

Here is more:
(C:\Users\Josh\Anaconda3) C:\Program Files\csound-windows-x64\bin>python C:\csoundcode\shapes.py
0dBFS level = 32768.0
--Csound version 6.11 (double samples) May 11 2018
[commit: eabe0dc8662062d4f9fd7cfcd6d9bbb2d286a495]
libsndfile-1.0.29pre1

error: syntax error, unexpected T_IDENT  (token "faustcompile") line 10:
>>>    ihandle faustcompile  <<<
Unexpected untyped word ihandle when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure

**Comment by kunstmusik** [comment]
The Csound installer for Windows does not include the Faust opcodes.  (I am
not sure if anyone has ever built or tested that opcode library on Windows?
@vlazzarini might know more about this. )

**Comment by vlazzarini** [comment]
I don’t think these opcodes were ever built for Windows. I am not sure of the status of libfaust on Windows or even whether it can be built with Visual C++, the same for llvm, which is one of its dependencies.

The faust opcodes have been build on MacOS and Linux, platforms where libfaust is actively supported. 

Unfortunately, I can’t help much more since I do not have a Windows machine.

**Comment by jcaballi** [comment]
Thank you for the responses. I'm installing Ubuntu right now on an unused machine and will hopefully get things working. That seemed cheaper than buying a Mac.

**Comment by jcaballi** [comment]
I've now installed Csound 6.12 on Ubuntu 17.1 and the Faust opcodes are not present when I run Csound -z from the terminal.

**Comment by vlazzarini** [comment]
Looks like you need to build these yourself, or ask the ubuntu package maintainers to provide them.

**Comment by maurocsound** [comment]
Finally today I were able to compile libfaust on a Windows 10 64bit machine. There were some little problems in compiling it using MSYS2, but thanks to the help of Dominique Fober, one of the Faust authors (a very kind and patient guy), now the compiling works without problems. The library is compiled with LLVM support.
Now I should try in building Csound (with faust opcodes) from the sources...

**Comment by vlazzarini** [comment]
Ok, you might not need to build all of Csound. With the headers installed (not sure if the windows installer installs these,
but you can check), and faustopcodes.cpp, all you need is to do:

g++ -03 -shared -o faustops.dll faustopcodes.cpp -I <path to csound headers> -lfaust

assuming faust lib is installed somewhere where gcc can find it.

**Comment by maurocsound** [comment]
Where is faustopcodes.cpp? I only see faustgen.cpp inside the Opcodes dir...

**Comment by vlazzarini** [comment]
faustgen.cpp is the right name

**Comment by maurocsound** [comment]
```
$ g++ -O3 -shared -o faustops.dll faustgen.cpp -l -lfaust
faustgen.cpp:37:10: fatal error: csdl.h: No such file or directory
 #include "csdl.h"
          ^~~~~~~~
compilation terminated.
```

**Comment by vlazzarini** [comment]
It can't find the Csound headers, you need to pass the correct option to g++ (see my comment above). Do you have experience using g++ in the commandline? Otherwise you will need to look up some help on compiler options.

**Comment by maurocsound** [comment]
Ok, I used the -I option to specify the include dir. Now:

```
$ g++ -O3 -shared -o faustops.dll faustgen.cpp -l -lfaust -I ../include
In file included from ../include/csoundCore.h:35:0,
                 from ../include/csdl.h:111,
                 from faustgen.cpp:37:
../include/sysdep.h:109:10: fatal error: float-version.h: No such file or directory
 #include "float-version.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

But "float-version.h" is only inside directory for iOS and Android... What is it?

**Comment by vlazzarini** [comment]
float-version.h is generated by CMake when Csound is built from sources, depending if it is built for floats or doubles. It doesn't exist in the sources before build. This is why I asked if the Csound Windows installer installs the headers as well. You need installed headers, not the ones directly from the source repo.
I would expect headers to be installed, but I don't know. Maybe @kunstmusik, @skyne would be able to confirm.

**Comment by maurocsound** [comment]
Unfortunately on Windows doesn't exist a default directory for header files, so, generally, you have to check inside the installation folder of the program.
Infact, if you install Csound from the full installer exe (https://github.com/csound/csound/releases/download/6.11.0/Csound6.11.0-Windows_x64-installer.exe) you can find an include directory inside the installation dir of Csound: 

"C:\Program Files\Csound6_x64\include"

In this directory there is a file "float-version.h.in". Then, I found that there is another subdir "C:\Program Files\Csound6_x64\include\csound" where the file "float-version.h" exists without the '.in'.
If I use this dir, as the additional include dir for g++, then I have this:

```
$ g++ -O3 -shared -o faustops.dll faustgen.cpp -l -lfaust -I "C:/Program Files/Csound6_X64/include/csound"
faustgen.cpp:38:10: fatal error: faust/dsp/llvm-dsp.h: No such file or directory
 #include "faust/dsp/llvm-dsp.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

So I suppose I should let g++ know what static library it should use for LLVM... The problem is LLVM has 65 different static libraries (about 69MB)... What should I use for compiling faustgen.cpp?

**Comment by vlazzarini** [comment]
Make sure you pass the directory where libfaust is using -L<dir>

It looks like you are close to making this work now.

**Comment by stekyne** [comment]
Maybe we should try and include Faust with the Windows build? I'll take a look at adding it to the CI/Appveyor build.

**Comment by maurocsound** [comment]
> Can you check if FAUSTFLOAT is float or double. It could be that libfaust was built for floats instead of doubles.

Yes, now I have to understand how to compile a faust lib with double instead of float. I think there should be a make option to do that. I should ask Dominique Fober...

> Maybe we should try and include Faust with the Windows build?

That would be very nice... :-)

**Comment by maurocsound** [comment]
Ok, I placed the faustops.dll inside "C:\Program Files\Csound6_x64\plugins64" but the plugin didn't work. Then I placed the following libraries (required for the faust.exe compiler to work) inside "C:\Windows\System32" dir:

libfaust.dll
libffi-6.dll
libgcc_s_seh-1.dll
libstdc++-6.dll
libwinpthread-1.dll
LLVM.dll

Now it works!! But... There is a problem. The following code works fine:

```
<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>
sr  = 44100
ksmps = 256
nchnls  = 2
0dbfs   = 1

instr 1
	a1 init 10
	a2 init 2
	a3 init 0
	idsp, a3 faustgen "process=+;", a1, a2
	printk 1, a3[0]
endin

</CsInstruments>
<CsScore>
i1 0 2
</CsScore>
</CsoundSynthesizer>
```

But if I use **faustcompile**, Csound goes in tilt (it crashes or stalls indefinitely) as I run the code:

```
<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
	a1 init 10
	a2 init 2
	a3 init 0
	ihandle faustcompile "process=+;", "-vec -lv 1"
	idsp, a3 faustaudio ihandle, a1, a2
	printk 1, a3[0]
endin

</CsInstruments>
<CsScore>
i 1 0 2
</CsScore>
</CsoundSynthesizer>
```

What can it be? The opcodes faustcompile/faustaudio are those that I need most, being that I want to JIT-compile only time, and then execute many times a compiled faust program inside Csound.

**Comment by vlazzarini** [comment]
Not sure. I've run your second example here on MacOS and it works fine. I wonder if it is to do with the waiting for the compilation to finish. Try running faustcompile on a separate instrument first, then
start the sound, say 1 sec later

```
<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 2
gihandle faustcompile "process=+;", "-vec -lv 1"
endin

instr 1
	a1 init 10
	a2 init 2
	a3 init 0
	idsp, a3 faustaudio gihandle, a1, a2
	printk 1, a3[0]
endin

</CsInstruments>
<CsScore>
i 2  0  1
i 1   1  2
</CsScore>
```

**Comment by vlazzarini** [comment]
Ok, I've located some changes that were made to the sources by someone else that maybe have broken this. I'll see if I can change it.

**Comment by maurocsound** [comment]
Hi Victor, I see you modded faustgen.cpp and so I downloaded and recompiled it. Unfortunately the result is the same as before.

**Comment by vlazzarini** [comment]
Actually those changes were OK.  I've added a little message indicating successful compilation.  I suspect the problem to be in faustaudio where the code checks for an existing handle, but have not diagnosed it completely.

**Comment by maurocsound** [comment]
If I remove faustaudio Csound process doesn't hangs anymore, but it is normal that the returned handle from faustcompile is 0 ?

```
[...]
instr 1
	iHandle faustcompile "process=+;", "-vec -lv 1"
	print iHandle
endin
</CsInstruments>
<CsScore>
i 1  0  1
</CsScore>
```

The above code doesn't crash but the iHandle returned is always 0 and the text "Faust compiled successfully" does appear only rarely...

**Comment by vlazzarini** [comment]
I've modified the code so that faustaudio bails out if there isn't a valid compiled code (factory) within 10msec of it starting.

**Comment by maurocsound** [comment]
Now it doesn't compile:

```
$ g++ -O3 -shared -o faustops.dll faustgen.cpp -DFAUSTFLOAT=double -DUSE_DOUBLE -I"C:/Program Files/Csound6_X64/include/csound"  -I "C:/msys64/usr/local/include" -L/usr/local/lib -lfaust
faustgen.cpp: In function 'void* init_faustcompile_thread(void*)':
faustgen.cpp:327:46: error: lvalue required as left operand of assignment
   ATOMIC_SETP((int64_t *) p->hptr, ffactory->cnt);
                                              ^
faustgen.cpp:266:37: note: in definition of macro 'ATOMIC_SETP'
 #define ATOMIC_SETP(var, val) var = val;
                                     ^~~
faustgen.cpp: In function 'int32_t init_faustaudio(CSOUND*, faustgen*)':
faustgen.cpp:450:47: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
   while (ATOMIC_GET8P((int64_t *)p->code) == -1) {
                                               ^
```

**Comment by vlazzarini** [comment]
oh, you don't have atomics enabled. Add

-DHAVE_ATOMIC_BUILTIN 

to the command line

**Comment by maurocsound** [comment]
Ok now it compiles but csound continues to crash with faustcompile. 
The strange thing is that faustgen works always perfectly, so I don't understand why faustcompile should not work... Now I always receive -1 as the ihandle value.

**Comment by vlazzarini** [comment]
-1 means the code has not completed compilation. Is it faustcompile crashing or
faustaudio? The latter should bail out if the code is not compiled within 10msecs.

Another thing that may matter is that the opcode is compiled with mingw and Csound was built with MSVC. Not sure if any wires are crossed that way.

Faust code is always compiled on a separate thread, maybe there is an issue with threading. But that is also the case with faustgen.

**Comment by maurocsound** [comment]
Csound crashes also with only the faustcompile statement. 
If I add the statement with faustaudio, Csound complains that there is no factory available:

```
[...]
SECTION 1:
new alloc for instr 1:
INIT ERROR in instr 1: no factory available

idsp    a3      faustaudio      iHandle a1      a2
          B  0.000 - note deleted.  i1 had 1 init errors
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.              overall amps:  0.00000  0.00000
           overall samples out of range:        0        0
1 errors in performance
Elapsed time at end of performance: real: 2.272s, CPU: 2.273s
closing device
Successfully compiled faust code
```
And here it crashes and exits.
My libfaust.dll is compiled with MinGW64 too, then there could be some problems with threads? Maybe I should try to build Csound myself... I tried yesterday but I had some trouble with the package libmusicxml (I don't know if it's mandatory to compile Csound).

**Comment by vlazzarini** [comment]
I think the crash is because the opcode gets deinitialised before the thread compiling is done. Something must be holding it up. It could be the locks, which are not present in the faustgen opcode. If you know how to, you can try commenting out lines 289 and 294.

It is unlikely to be a threading problem
because faustgen also runs the compiler in a thread.

I think the issues are somewhere in the init_faustcompile_thread() function.

**Comment by maurocsound** [comment]
I tried to comment those lines but the result is the same:
INIT ERROR in instr 1: no factory available

Another strange thing is that with the first faustops.dll I compiled, sometimes (but rarely) it worked and never displayed that INIT ERROR. And the handle returned was always 0, not -1.

**Comment by vlazzarini** [comment]
I introduced the init error to allow faustaudio to bail out if faustcompile did not produce the code on time.

Try to move out the faustcompile line to outside the instrument (in global space). It could be that once the instr stops, it deletes the compiled factory.

**Comment by vlazzarini** [comment]
actually that is not happening, because the factories are only deleted at reset time.

**Comment by vlazzarini** [comment]
tomorrow, I'll add some tracing and we can check where the hold up is.

**Comment by maurocsound** [comment]
Ok, I used the faustgen.cpp from 27 June (commit from jpffitch: more minor changes to faustgen) and commented those lines on Lock and UnlockMutex.
Now Csound seems to always work without problems with faustcompile and faustaudio too!!

P.S.: the version with ATOMIC_BUILTIN didn't work when I commented those lines but this previous commit works!

**Comment by vlazzarini** [comment]
ok, the atomic stuff was a shot in the dark, I'll revert the code and remove those lines.

**Comment by maurocsound** [comment]
Unfortunately it's not perfect... I tried to use those opcodes inside a big csd file and when I run it, csound crashes 1 time every 3-4 runs.

Anyway, how can I do if I want to pass i-type or k-type parameters to a faust program? I think faustgen accepts only a-type variables as parameters...

**Comment by vlazzarini** [comment]
you have to use faustctl to do it, and build an interface in the faust program. 

If you copy here the crashing CSD here I can take a look.

**Comment by maurocsound** [comment]
Ok, thank you. :-)
When you need to make fast sample-by-sample computations and no actual opcode satisfy your needs, the idea is that you could make a little Faust program and then JIT-compile it at run-time (during the init-pass) so that you could write a very efficient UDO without having to create each time a C/C++ native code and compile it in a Csound plugin (not all the Csound users have the knowledge/expertise to do that, and, at least on a Windows machine, is very cumbersome to install all the development tools and make all the needed preparations to build a project from source code).

In this regard, I wanted to compare the execution speed of:

1) Csound native biquad opcode;
2) UDO version of biquad (with setksmps=1);
3) JIT-compiled Faust version.

I already know, from my tests, that (2) is very much slower than (1), so I wanted to compare it with (3). My thought is that, if the faust opcodes work as expected, (1) and (3) should be very similar, if not identical, in execution speed, and I wanted to test it.

So, I wanted to do something like that:

```
; BIQUAD implementation as a JIT-compiled Faust expression:
giBQhandle faustcompile {{
	process(xn,b0,b1,b2,a0,a1,a2) = 
		((b0*xn + b1*xn' + b2*xn'' - _) / a0) ~ (_ <: (a1*_ + a2*_'));
}}, "-vec -lv 1"

opcode faustBiquad a, akkkkkk
	aXn, kb0, kb1, kb2, ka0, ka1, ka2 xin

    	idsp, aYn faustaudio giBQhandle, aXn, kb0, kb1, kb2, ka0, ka1, ka2
	xout aYn
endop
```

But of course, inside the faust program, b0,b1,b2,a0,a1,a2 should be numbers, not vectors... How can I do that?

**Comment by vlazzarini** [comment]
you will need to set up an interface in the faust program and access it via faustctl. That will pass control (scalar) variables to the faust program. That's the way faust works

https://csound.com/docs/manual/faustctl.html

btw I've added faustcompile2 which is exactly like faustcompile but blocks until the code is compiled. The best use of it is by placing it in the header so that the compilation is done before Csound starts running.

**Comment by maurocsound** [comment]
Mmmmh... So it should be like the following code...?

```
; BIQUAD implementation as a JIT-compiled Faust expression:
giBQhandle faustcompile {{
	b0 = nentry("b0",0,0,1,0.001);
	b1 = nentry("b1",0,0,1,0.001);
	b2 = nentry("b2",0,0,1,0.001);
	a0 = nentry("a0",0,0,1,0.001);
	a1 = nentry("a1",0,0,1,0.001);
	a2 = nentry("a2",0,0,1,0.001);
	process(xn) = 
		((b0*xn + b1*xn' + b2*xn'' - _) / a0) ~ (_ <: (a1*_ + a2*_'));
}}, "-vec -lv 1"

opcode faustBiquad, a, akkkkkk
	aXn, kb0, kb1, kb2, ka0, ka1, ka2 xin
    
	idsp, aYn faustaudio giBQhandle, aXn
    
 	faustctl idsp, "b0", kb0
 	faustctl idsp, "b1", kb1
	faustctl idsp, "b2", kb2
	faustctl idsp, "a0", ka0
	faustctl idsp, "a1", ka1
	faustctl idsp, "a2", ka2
    
 	xout aYn
endop
```

But there is something I don't understand... I suppose I should set the control parameters for the faust instance "before" its execution with faustaudio... But I cannot do that until I get the idsp handle with faustaudio... So, it's like a cat chasing its tail...

**Comment by vlazzarini** [comment]
That's how it is. The dsp has to be
instantiated for the controls to be accessible. The controls will be one k-cycle
behind, which is not usually a problem.
You might want to give some initial values in the Faust code if you need to.

**Comment by vlazzarini** [comment]
I've added two new opcodes, splitting the DSP instantiation and performance. So now, it is possible to insert the controls before the performance in an instrument:

```
gihandle2 faustcompile2 {{
   gain = hslider("vol",1,0,1,0.01);
   process = (_ * gain); 
  }}, "-vec -lv 1"

instr 1
 k1 line  0, p3, 1
 idsp faustdsp gihandle2
 faustctl idsp, "vol", k1
 ain1 oscili 0dbfs/2, 440
 a1 faustplay idsp, ain1
   out a1
endin
```

faustdsp instantiates the dsp and gives a handle to it. faustplay runs the dsp. Together they are the same as faustaudio. For each faustplay you need a separate faustdsp.

**Comment by maurocsound** [comment]
Great! 👍

**Comment by maurocsound** [comment]
I have to specify the vector size with "-vec -vs <KSMPS>" as the second parameter of faustcompile? And what that -lv 1 is for? On the faust quick-reference manual it says that the default is 0 (fastest).

**Comment by maurocsound** [comment]
Nice, thanks! :-)

**Comment by maurocsound** [comment]
It would be hard to make a faustctl version that allows to pass more parameters to the faust instance?

From my tests I think that when you have many parameters to pass to the faust compiled instance, the following passage of parameters could slow down the run-time performance considerably:

	faustctl 	idsp, "b0", ib0
	faustctl 	idsp, "b1", ib1
	faustctl 	idsp, "b2", ib2
	faustctl	idsp, "a0", ia0
	faustctl 	idsp, "a1", ia1
	faustctl 	idsp, "a2", ia2

So, I think this could be more efficient at run-time, because in the Csound traversal of the chained link of opcode nodes at run-time, the Csound parser would have to traverse only one node, instead of 6:

	faustctl 	idsp,  "b0", ib0,  "b1", ib1,  "b2", ib2,  "a0", ia0,  "a1",ia1,  "a2", ia2 

This could save precious computation time inside a digital waveguide loop code. I'm making some comparing tests between the runtime performance of a native biquad opcode, a Csound implementation, and a Faust JIT-compiled one, and soon I will publish them.

**Comment by maurocsound** [comment]
Of course in my example faustctl should do its work only at i-time, so it's a waste of processing power to make it run at k-time too... But if you have a situation where you need to pass the params at each k iteration, than a "one-line multi-parameter" faustctl statement could still be useful, I think.

**Comment by vlazzarini** [comment]
Ok, the faustctl i-time is there now. I'll look on how to enable multiple parameters later on

**Comment by maurocsound** [comment]
Thanks, I tried your mods. To me it appears that the execution speed is not changed from before. Anyway I want to share with you the results from my experiments. 

## PREMISES
The test is based on a csd file (you can find it at the bottom of this post) that implements a very simple digital waveguide loop (it's the usual Karplus-Strong style loop). The basic loss-filter "y[n] = (x[n] + x[n-1]) / 2" is implemented with a biquad so that I could do some comparisons. For simplicity there is no fine-tuning to compensate for the approximation in the digital delay line length.

The global ksmps is set to 32. To put Csound under pressure, the biquad is applied 30 times in cascade at each iteration. To make this I created a recursive UDO, named cascBQ.

## THE TEST
Now, the test simply consists in checking how much notes you can play in polyphony, before you hear clicks and artifacts in the output signal. I run the code in CsoundQT editor which has a nice virtual keyboard that let me play the notes with the PC keyboard or with the mouse. You can see in the output console area the number of notes you have in polyphony. To facilitate polyphony testing, each note instance lasts 20 seconds (so you have all the time to play the notes and test the max polyphony you can reach on your PC).

## THE RESULTS
Using biquad native opcodes, on an Intel CPU i7 forced to always stay at its minimum frequency (0.78GHz), I achieved a max of 22 notes in polyphony without artifacts.

Replacing the "biquad" native opcode with an UDO that does the same thing, but written in Csound language, I could only play ONE note without audible artifacts!

Replacing the "biquad" native opcode with Csound code that pass the params to an instance of a JIT-compiled Faust code and runs it, I could achieve 11 notes in polyphony. It's way better than the Csound version, but it's half the speed of the native one.

Now, if in the last example I remove the lines that pass the i-type params to the Faust program instance I achieve 18 notes in polyphony without artifacts, that is very similar to the 22 notes of the native biquad version!

Therefore, summarizing, this is the situation:

- Csound version: about 4-5% the native speed.
- Faust ver. with faustctl params passing: 50% the native speed.
- Faust ver. without faustctl params passing: about 82% the native speed.

## THE CSD FILE
```

<CsoundSynthesizer>
<CsOptions>
;-odac -d
-n -d -+rtmidi=NULL -M0 -m0d --midi-key-cps=4 --midi-velocity-amp=5
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs =  1

; A biquad implementation in Csound language:
; P.S.: from my experiments, this 'setksmps 1' verions is faster than an implementation 
;        that directly changes the elements of the a-rate input vector within a while loop iteration.
opcode csndBQ, a, aiiiiii
	axn, ib0, ib1, ib2, ia0, ia1, ia2 xin
	setksmps 1
	
	kxn_1	init	0 ; x[n-1]
	kxn_2	init	0 ; x[n-2]
	kyn_1	init	0 ; y[n-1]
	kyn_2	init	0 ; y[n-2]
	
	ayn	=	(ib0 * axn + ib1 * kxn_1 + ib2 * kxn_2 - ia1 * kyn_1 - ia2 * kyn_2) / ia0
	
	kxn_2	=	kxn_1
	kxn_1	=	axn[0]
	kyn_2	=	kyn_1
	kyn_1	=	ayn[0]
	
		xout	ayn
endop

; A BIQUAD implementation as a Faust expression with params... Let's compile it:
giBQhandle faustcompile2 {{
	b0 = nentry("b0",0.5,0,1,0.001);
	b1 = nentry("b1",0.5,0,1,0.001);
	b2 = nentry("b2",0,0,1,0.001);
	a0 = nentry("a0",1,0,1,0.001);
	a1 = nentry("a1",0,0,1,0.001);
	a2 = nentry("a2",0,0,1,0.001);
	process(xn) = 
		((b0*xn + b1*xn' + b2*xn'' - _) / a0) ~ (_ <: (a1*_ + a2*_'));
}}, "-vec"

; using NATIVE biquad opcode:
opcode cascBQ1, a, aiiiiiip
	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN xin
	
	if (iN > 0) then
		aSignal	biquad	aSignal, ib0, ib1, ib2, ia0, ia1, ia2
    		aSignal	cascBQ1	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN - 1
	endif
	
		xout	aSignal
endop

; using biquad implemented in Csound language:
opcode cascBQ2, a, aiiiiiip
	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN xin
	
	if (iN > 0) then
		aSignal	csndBQ	aSignal, ib0, ib1, ib2, ia0, ia1, ia2
    		aSignal	cascBQ2	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN - 1
	endif
	
		xout	aSignal
endop

; using a JIT-compiled faust code with i-type parameters passed by faustctl:
opcode cascBQ3, a, aiiiiiip
	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN xin
	
	if (iN > 0) then
		idsp 	faustdsp	giBQhandle
	    		faustctl	idsp, "b0", ib0
	    		faustctl	idsp, "b1", ib1
	    		faustctl	idsp, "b2", ib2
	    		faustctl	idsp, "a0", ia0
	    		faustctl	idsp, "a1", ia1
	    		faustctl	idsp, "a2", ia2
	    aSignal	faustplay	idsp, aSignal
    	    aSignal	cascBQ3	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN - 1
	endif
	
		xout	aSignal
endop

; using a JIT-compiled faust code without i-type params passing:
opcode cascBQ4, a, aiiiiiip
	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN xin
	
	if (iN > 0) then
		idsp 	faustdsp	giBQhandle
		; NO PARAMS PASSED TO THE FAUST CODE INSTANCE!
	    aSignal	faustplay	idsp, aSignal
    	    aSignal	cascBQ4	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN - 1
	endif
	
		xout	aSignal
endop

instr 1
	aNoise 		rand 	p5, 0.5
	iDelayLdur 	= 	1 / p4
	aLine 		linseg 	1, iDelayLdur, 1, 0, 0
	aDL		delayr 	iDelayLdur
	aDL		+= 	aNoise * aLine
	; for the test use one of the following cascBQx versions, commenting the others:
	aDL 		cascBQ1	aDL, 0.5, 0.5, 0, 1, 0, 0,  30 ; native biquad
	;aDL 		cascBQ2	aDL, 0.5, 0.5, 0, 1, 0, 0,  30 ; Csound biquad
	;aDL 		cascBQ3	aDL, 0.5, 0.5, 0, 1, 0, 0,  30 ; Faust biquad with params passing
	;aDL 		cascBQ4	aDL, 0.5, 0.5, 0, 1, 0, 0,  30 ; Faust biquad without par.passing
			delayw 	aDL
				
	aDL		=	aDL * madsr(0.001, 0, 1, 20)
			outs 	aDL, aDL
endin

instr Monitor
			printk2	active:k(1) ; <-- display the currently active notes in polyphony
endin

</CsInstruments>
<CsScore>
f 0 z
i "Monitor" 0 z
</CsScore>
```

**Comment by vlazzarini** [comment]
Thanks. I wonder about your UDO, and I looked at the biquad code. A closer comparison would be this

```
opcode csndBQ, a, aiiiiii
	axn, ib0, ib1, ib2, ia0, ia1, ia2 xin
	setksmps 1
	
	axn_1	init	0 ; x[n-1]
	axn_2	init	0 ; x[n-2]
         ayn_1	init	0 ; y[n-1]
	ayn_2	init	0 ; y[n-2]
	
	ib0 = ib0/ia0
	ib1 = ib1/ia0
	ib2 = ib2/ia0
	ia1 = ia1/ia0
	ia2 = ia2/ia0 
	
	ayn	=	 ib0 * axn + ib1 * axn_1 + ib2 * axn_2 - ia1 * ayn_1 - ia2 * ayn_2
	
	axn_2	=	axn_1
	axn_1	=	axn
	ayn_2	=	ayn_1
	ayn_1	=	ayn
	
		xout	ayn
endop
```
which runs about 30% faster than your original code. Compared to biquad, it runs 7 times slower. The timings for a 100 sec run on a simple instrument only running this opcode are

0.118 - biquad
0.723 - the UDO above
0.922 - the UDO in your example

I'll test your code later here.

**Comment by vlazzarini** [comment]
I had a play with your instrument here, and what I found was that the 20 sec release time of madsr was masking things. If I play one note in quick succession, several instances of the instrument would build up and we get overruns. By reducing the release time to 0.1, and avoiding overlaps I was able to play 4-note chords with no dropouts. I think that is about what I would expect with 30 biquads in cascade for each instance. Thanks again for the comparison.

**Comment by maurocsound** [comment]
Hi Victor, nice optimization for the Csound biquad UDO, especially to avoid dividing by ia0 at each k-iteration, but theorically speaking I don't understand why using 1-sample-size a-type variables should be faster than using a k-type variable...

**Comment by maurocsound** [comment]
As I suspected, one of the performance problem of my implementation was in these:

```
kxn_1	=	axn[0]
kyn_1	=	ayn[0]
```

If I replace them with:

```
kxn_1	vaget	0, axn
kyn_1	vaget	0, ayn
```

Together with the "/ia0" optimization, my UDO will regain that ~30% in speed...

Why is that? I think because "kxn_1 = axn[0]" translates in more nodes to parse inside Csound engine, something like:

```
kTempVar vaget 0, axn
kxn_1 = kTempVar
```
So, in my initial version, those two lines of codes at run-time were like 4! 

Maybe my little Faust program could be optimized too (I'm a very beginner on Faust language).

**Comment by maurocsound** [comment]
You said:

> I had a play with your instrument here, and what I found was that the 20 sec release time of madsr was masking things. If I play one note in quick succession, several instances of the instrument would build up and we get overruns.

Yes, the note sound ends in a few seconds, but its instance lasts for 20 seconds... In fact, that 20sec release time was to easily instantiate many notes in polyphony without having dozens of fingers for pressing many keys simultaneously... Just press random keys in quick succession and the polyphony will build up until the CPU is not able anymore to fill the audio buffer in time... That is the signal that you exceeded the max polyphony allowed by your computer. This is how I intended the test.

**Comment by maurocsound** [comment]
### UPDATE on the previous tests:

I optimized the Faust version too, so that now it doesn't have to divide by a0 at each sample computation, exactly as the optimization Victor made in the Csound version. Now we have:

- Csound version: about 4-5% the native speed.
- Faust ver. with faustctl params passing: ~59% the native speed.
- Faust ver. without faustctl params passing: ~95% the native speed.

Here follows the modded code (there is also a new csndBQ opcode with the optimizations):

```
; A biquad implementation in Csound language:
; P.S.: from my experiments, this 'setksmps 1' verions is faster than an implementation that directly changes the elements of the a-rate input vector within a while loop iteration.
opcode csndBQ, a, aiiiiii
	axn, ib0, ib1, ib2, ia0, ia1, ia2 xin
	setksmps 1
	
	kxn_1	init	0 ; x[n-1]
	kxn_2	init	0 ; x[n-2]
	kyn_1	init	0 ; y[n-1]
	kyn_2	init	0 ; y[n-2]
	
	ib0	/=	ia0
	ib1	/=	ia0
	ib2	/=	ia0
	ia1	/=	ia0
	ia2	/=	ia0
	
	ayn	=	(ib0 * axn + ib1 * kxn_1 + ib2 * kxn_2 - ia1 * kyn_1 - ia2 * kyn_2)
	
	kxn_2	=	kxn_1
	kxn_1	vaget	0, axn ; faster than "kxn_1 = axn[0]"
	kyn_2	=	kyn_1
	kyn_1	vaget	0, ayn ; faster than "kyn_1 = ayn[0]"
	
		xout	ayn
endop


; A BIQUAD implementation as a Faust expression with params... Let's compile it:
; (P.S.: to achieve better performance, this version supposes b0,b1,b2,a1,a2 are 
;  already divided by a0)
giBQhandle faustcompile2 {{
	b0 = nentry("b0",0.5,0,1,0.001);
	b1 = nentry("b1",0.5,0,1,0.001);
	b2 = nentry("b2",0,0,1,0.001);
	a1 = nentry("a1",0,0,1,0.001);
	a2 = nentry("a2",0,0,1,0.001);
	process(xn) = 
		(b0*xn + b1*xn' + b2*xn'' - _) ~ (_ <: (a1*_ + a2*_'));
}}, "-vec"

; using a JIT-compiled faust code with i-type parameters passed by faustctl:
opcode cascBQ3, a, aiiiiip
	aSignal, ib0, ib1, ib2, ia1, ia2, iN xin
	
	if (iN > 0) then
		idsp 	faustdsp	giBQhandle
	    		faustctl 	idsp, "b0", ib0
	    		faustctl 	idsp, "b1", ib1
	    		faustctl 	idsp, "b2", ib2
	    		faustctl 	idsp, "a1", ia1
	    		faustctl 	idsp, "a2", ia2
		aSignal	faustplay 	idsp, aSignal
		aSignal	cascBQ3		aSignal, ib0, ib1, ib2, ia1, ia2, iN - 1
	endif
	
		xout	aSignal
endop

instr 1
	aNoise 		rand 	p5 / 2, 0.5
	iDelayLdur	=	1 / p4
	aLine		linseg 	1, iDelayLdur, 1, 0, 0
	aDL		delayr 	iDelayLdur
	aDL		+=	aNoise * aLine
	; for the test use one of the following cascBQx versions, commenting the others:
	;aDL		cascBQ1	aDL, 0.5, 0.5, 0, 1, 0, 0,  30 ; native biquad
	;aDL 		cascBQ2	aDL, 0.5, 0.5, 0, 1, 0, 0,  30 ; Csound biquad
	aDL 		cascBQ3	aDL, 0.5, 0.5, 0, 0, 0,  30 ; Faust biquad with params passing
	;aDL 		cascBQ4	aDL, 0.5, 0.5, 0, 1, 0, 0,  30 ; Faust biquad without par.passing
			delayw 	aDL
				
	aDL		=	aDL * madsr(0.001, 0, 1, 20)
				outs 	aDL, aDL
endin
```

**Comment by maurocsound** [comment]
> I wonder whether you can offer the faustgen.dll for download to other Windows users, such as @jcaballi
> who might be looking for it. I suspect you will need to supply libfaust.dll (if you have built faust as
> a dll, otherwise not). I think you might be able to upload a zip file to this issue.

I attached a zip file.

There are the DLLs that should be placed inside the C:\Windows\System32 dir:
```
libfaust.dll
LLVM.dll
libffi-6.dll
libgcc_s_seh-1.dll
libwinpthread-1.dll
libstdc++-6.dll
```

Instead, "faustops.dll" should be placed in C:\Program Files\Csound6_x64\plugins64


[Faust DLLs for Csound.zip](https://github.com/csound/csound/files/2320956/Faust.DLLs.for.Csound.zip)

**Comment by vlazzarini** [comment]
Excellent, thanks.

**Comment by jpffitch** [comment]
Is this issue resolved?  It seems to have evolved from the original post and I cannot work out the status

**Comment by jcaballi** [comment]
Thanks! Much appreciated.

**Comment by maurocsound** [comment]
> Is this issue resolved? It seems to have evolved from the original post and I cannot work out the status

It is solved in part. The problem is that the Windows build doesn't include the faust lib because there were (or there still are?) some problems in compiling faust and llvm libs with MSVC. I managed to compile them within "MSYS2 MinGW 64-bit" and they work (I attached a zip file in a previous message), but it's not a definitive solution, being that the mantainers of the Windows package use MSVC.

This issue is closely related to: https://github.com/csound/csound/issues/997
