### ISSUE TITLE
Could not find or load the Qt platform plugin "windows" in "".

### ISSUE THREAD

**Issue by scolbio** [csound/csound#972]
Hi Ive downloaded Csound 6.11 bundled with CsoundQT. When I try to run CsoundQT I get this message:

This application failed to start because it could not find or load the Qt platform plugin "windows" in "".

Reinstalling the application may fix the problem.

I'm on 64-bit Windows Vista. Any ideas?

Thanks

**Comment by kunstmusik** [comment]
I found a relevant issue reported with another QT-related project here:

https://github.com/mmozeiko/RcloneBrowser/issues/59

Seems QT stopped supporting Windows Vista with QT 5.6.  We are only packaging the version of CsoundQT released by CsoundQT developers and I assume they are using a version of QT than 5.6. It would be up to the developers there to address the issue.  (I don't know if they are using features that require a newer QT version or not.)

For now, I will close this issue here and recommend filing an issue with the CsoundQT project tracker: https://github.com/CsoundQt/CsoundQt/issues 

If the developers there work out something, please then file a new issue here to update the Csound installer to package a newer CsoundQt release once they have something posted.  We can then update our Windows installer build scripts to use their newer build. 

(@joachimheintz FYI, this issue may be coming over to the CsoundQt tracker)

**Comment by scolbio** [comment]
Ok thanks
